In [1]:
import pandas as pd
df=pd.read_csv('cars.csv',encoding='cp1252')
df

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÃœRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21
5,2016-04-04 17:36:23,BMW_316i___e36_Limousine___Bastlerfahrzeug__Ex...,privat,Angebot,650,test,limousine,1995,manuell,102,3er,150000,10,benzin,bmw,ja,2016-04-04 00:00:00,0,33775,2016-04-06 19:17:07
6,2016-04-01 20:48:51,Peugeot_206_CC_110_Platinum,privat,Angebot,2200,test,cabrio,2004,manuell,109,2_reihe,150000,8,benzin,peugeot,nein,2016-04-01 00:00:00,0,67112,2016-04-05 18:18:39
7,2016-03-21 18:54:38,VW_Derby_Bj_80__Scheunenfund,privat,Angebot,0,test,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein,2016-03-21 00:00:00,0,19348,2016-03-25 16:47:58
8,2016-04-04 23:42:13,Ford_C___Max_Titanium_1_0_L_EcoBoost,privat,Angebot,14500,control,bus,2014,manuell,125,c_max,30000,8,benzin,ford,NaN,2016-04-04 00:00:00,0,94505,2016-04-04 23:42:13
9,2016-03-17 10:53:50,VW_Golf_4_5_tuerig_zu_verkaufen_mit_Anhaengerk...,privat,Angebot,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN,2016-03-17 00:00:00,0,27472,2016-03-31 17:17:06
10,2016-03-26 19:54:18,Mazda_3_1.6_Sport,privat,Angebot,2000,control,limousine,2004,manuell,105,3_reihe,150000,12,benzin,mazda,nein,2016-03-26 00:00:00,0,96224,2016-04-06 10:45:34
11,2016-04-07 10:06:22,Volkswagen_Passat_Variant_2.0_TDI_Comfortline,privat,Angebot,2799,control,kombi,2005,manuell,140,passat,150000,12,diesel,volkswagen,ja,2016-04-07 00:00:00,0,57290,2016-04-07 10:25:17
12,2016-03-15 22:49:09,"VW_Passat_Facelift_35i__""7Sitzer""",privat,Angebot,999,control,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,NaN,2016-03-15 00:00:00,0,37269,2016-04-01 13:16:16
13,2016-03-21 21:37:40,VW_PASSAT_1.9_TDI_131_PS_LEDER,privat,Angebot,2500,control,kombi,2004,manuell,131,passat,150000,2,NaN,volkswagen,nein,2016-03-21 00:00:00,0,90762,2016-03-23 02:50:54
14,2016-03-21 12:57:01,Nissan_Navara_2.5DPF_SE4x4_Klima_Sitzheizg_Blu...,privat,Angebot,17999,control,suv,2011,manuell,190,navara,70000,3,diesel,nissan,nein,2016-03-21 00:00:00,0,4177,2016-04-06 07:45:42
15,2016-03-11 21:39:15,KA_Lufthansa_Edition_450â‚¬_VB,privat,Angebot,450,test,kleinwagen,1910,NaN,0,ka,5000,0,benzin,ford,NaN,2016-03-11 00:00:00,0,24148,2016-03-19 08:46:47
16,2016-04-01 12:46:46,Polo_6n_1_4,privat,Angebot,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN,2016-04-01 00:00:00,0,38871,2016-04-01 12:46:46
17,2016-03-20 10:25:19,Renault_Twingo_1.2_16V_Aut.,privat,Angebot,1750,control,kleinwagen,2004,automatik,75,twingo,150000,2,benzin,renault,nein,2016-03-20 00:00:00,0,65599,2016-04-06 13:16:07
18,2016-03-23 15:48:05,Ford_C_MAX_2.0_TDCi_DPF_Titanium,privat,Angebot,7550,test,bus,2007,manuell,136,c_max,150000,6,diesel,ford,nein,2016-03-23 00:00:00,0,88361,2016-04-05 18:45:11
19,2016-04-01 22:55:47,Mercedes_Benz_A_160_Classic_Klima,privat,Angebot,1850,test,bus,2004,manuell,102,a_klasse,150000,1,benzin,mercedes_benz,nein,2016-04-01 00:00:00,0,49565,2016-04-05 22:46:05
20,2016-04-01 19:56:48,Volkswagen_Scirocco_1.4_TSI_Sport,privat,Angebot,10400,control,coupe,2009,manuell,160,scirocco,100000,4,benzin,volkswagen,nein,2016-04-01 00:00:00,0,75365,2016-04-05 16:45:49
21,2016-03-27 11:38:00,BMW_530i_TÃœV_7/17_Scheckheftgepflegt_sehr_gute...,privat,Angebot,3699,test,limousine,2002,automatik,231,5er,150000,7,benzin,bmw,nein,2016-03-27 00:00:00,0,68309,2016-04-07 06:44:26
22,2016-03-23 14:52:51,Opel_Meriva_1.Hand_TÃœV_3.2018,privat,Angebot,2900,test,NaN,2018,manuell,90,meriva,150000,5,benzin,opel,nein,2016-03-23 00:00:00,0,49716,2016-03-31 01:16:33
23,2016-03-12 19:43:07,Stadtflitzer,privat,Angebot,450,test,kleinwagen,1997,manuell,50,arosa,150000,5,benzin,seat,nein,2016-03-12 00:00:00,0,9526,2016-03-21 01:46:11
24,2016-03-13 20:40:49,MERCEDES_200E__TÃœV_04/2016,privat,Angebot,500,test,limousine,1990,manuell,118,andere,150000,10,benzin,mercedes_benz,ja,2016-03-13 00:00:00,0,35390,2016-03-13 20:40:49
25,2016-03-18 21:44:09,BMW_530d_touring_Vollausstattung_NAVI,privat,Angebot,2500,control,kombi,2002,automatik,193,5er,150000,9,diesel,bmw,ja,2016-03-18 00:00:00,0,73765,2016-03-18 21:44:09
26,2016-03-10 19:38:18,Citroen_C4_Grand_Picasso.,privat,Angebot,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein,2016-03-10 00:00:00,0,31139,2016-03-16 09:16:46
27,2016-03-07 12:51:23,Honda_Civic_1.4_i_VTEC_Comfort,privat,Angebot,6900,test,limousine,2008,manuell,99,civic,60000,11,benzin,honda,nein,2016-03-07 00:00:00,0,12621,2016-03-26 09:44:53
28,2016-03-09 11:56:38,Volkswagen_T3_andere,privat,Angebot,1990,test,bus,1981,manuell,50,transporter,5000,1,benzin,volkswagen,nein,2016-03-09 00:00:00,0,87471,2016-03-10 07:44:33
29,2016-03-08 19:55:19,Fiat_Punto_1.2,privat,Angebot,690,test,kleinwagen,2003,manuell,60,punto,150000,3,benzin,fiat,nein,2016-03-08 00:00:00,0,86199,2016-03-09 11:45:28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371498,2016-03-11 15:50:38,Opel_Vectra_Edition_100,privat,Angebot,699,control,limousine,1999,manuell,101,vectra,150000,3,benzin,opel,NaN,2016-03-11 00:00:00,0,65936,2016-03-17 12:44:29
371499,2016-03-08 13:52:00,OPEL_CORSA_B__ECO_SWING__TÃœV_1/17_8fach_Bereif...,privat,Angebot,600,control,kleinwagen,1998,manuell,54,corsa,150000,1,benzin,opel,nein,2016-03-08 00:00:00,0,24850,2016-03-13 00:16:40
371500,2016-03-21 23:40:49,Volkswagen_Golf_1.4_TSI_BlueMotion_Technology_...,privat,Angebot,20400,test,limousine,2014,automatik,150,golf,30000,9,benzin,volkswagen,nein,2016-03-21 00:00:00,0,38470,2016-04-07 04:17:32
371501,2016-03-26 18:36:54,Chrysler_Voyager,privat,Angebot,3900,test,bus,2003,automatik,174,voyager,150000,7,benzin,chrysler,nein,2016-03-26 00:00:00,0,34320,2016-04-06 09:16:04
371502,2016-04-01 12:59:21,Audi_A4_Avant_1.8,privat,Angebot,1600,test,kombi,1998,manuell,125,a4,150000,2,benzin,audi,nein,2016-04-01 00:00:00,0,34414,2016-04-07 09:44:29
371503,2016-04-01 01:55:58,Subaru_Justy_1.3,privat,Angebot,1700,control,kleinwagen,1999,manuell,68,justy,70000,11,benzin,subaru,nein,2016-03-31 00:00:00,0,90439,2016-04-07 04:16:26
371504,2016-03-07 17:06:35,220_cdi_Benz,privat,Angebot,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN,2016-03-07 00:00:00,0,61169,2016-03-08 21:28:38
371505,2016-04-03 19:56:57,Opel_Astra_1.6_Caravan_Selection,privat,Angebot,800,test,kombi,2000,manuell,101,astra,150000,11,benzin,opel,ja,2016-04-03 00:00:00,0,58730,2016-04-05 20:45:39
371506,2016-03-20 18:47:59,Volkswagen_Golf_1.9_TDI_DPF_Goal_Rentnerfzg._1...,privat,Angebot,5900,test,limousine,2006,manuell,105,golf,150000,9,diesel,volkswagen,nein,2016-03-20 00:00:00,0,1217,2016-04-07 02:44:27
371507,2016-03-16 17:06:19,Gepflegter_Audi_a4_2.0tdi_xenon_ahk_klima_sche...,privat,Angebot,5999,test,kombi,2005,manuell,140,a4,150000,4,diesel,audi,NaN,2016-03-16 00:00:00,0,56472,2016-03-18 11:30:17
371508,2016-04-02 16:43:27,Opel_Astra_1.8,privat,Angebot,1400,control,limousine,2001,manuell,125,astra,150000,2,benzin,opel,nein,2016-04-02 00:00:00,0,23820,2016-04-06 15:18:04
371509,2016-03-11 23:40:32,LT_35_DIESEL_Gruene_Plakette....letzte_Gelegen...,privat,Angebot,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein,2016-03-11 00:00:00,0,87700,2016-03-12 14:16:51
371510,2016-03-06 21:11:23,Mercedes_benz_e_klasse_avangarde_220_cdi_grune...,privat,Angebot,6500,test,limousine,2003,automatik,145,e_klasse,150000,3,diesel,mercedes_benz,nein,2016-03-05 00:00:00,0,60437,2016-03-12 12:18:05
371511,2016-03-31 18:50:37,Audi_A3_1.8_T_Attraction,privat,Angebot,1999,control,limousine,1997,manuell,150,a3,150000,12,benzin,audi,nein,2016-03-31 00:00:00,0,4275,2016-04-06 12:46:41
371512,2016-03-25 18:48:06,Mercedes_Benz_E_400_CDI_Avantgarde,privat,Angebot,5000,test,limousine,2003,automatik,260,e_klasse,150000,12,diesel,mercedes_benz,ja,2016-03-25 00:00:00,0,90473,2016-04-07 00:44:51
371513,2016-03-21 15:36:22,Seat_Leon_1.9_TDI_4/5_Tueren,privat,Angebot,4400,control,limousine,2008,manuell,105,leon,150000,7,diesel,seat,nein,2016-03-21 00:00:00,0,45896,2016-04-06 15:45:01
371514,2016-04-04 11:45:16,Renault_1_4_ltr.16_V_Megane_Cabrio,privat,Angebot,999,control,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,NaN,2016-04-04 00:00:00,0,88477,2016-04-06 12:44:52
371515,2016-03-09 11:36:55,Skoda_Fabia_Kombi_1.4,privat,Angebot,1690,test,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,NaN,2016-03-09 00:00:00,0,18246,2016-04-04 08:15:30
371516,2016-04-04 09:57:12,Volkswagen_Lupo_1.0,privat,Angebot,1490,control,kleinwagen,1998,manuell,50,lupo,150000,9,benzin,volkswagen,nein,2016-04-04 00:00:00,0,48653,2016-04-06 11:17:13
371517,2016-03-28 13:48:07,Volkswagen_Golf_2.0_TDI_DPF_Team,privat,Angebot,7900,test,limousine,2010,manuell,140,golf,150000,7,diesel,volkswagen,nein,2016-03-28 00:00:00,0,75223,2016-04-02 18:16:20
371518,2016-04-02 20:37:03,Bmw_320_D_DPF_Touring_!!!,privat,Angebot,3999,test,kombi,2005,manuell,3,3er,150000,5,diesel,bmw,nein,2016-04-02 00:00:00,0,81825,2016-04-06 20:47:12
371519,2016-03-09 13:37:43,Alfa_Romeo_159_Jtdm_1.9_150_ps_13_600_km_top_voll,privat,Angebot,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein,2016-03-09 00:00:00,0,51371,2016-03-13 01:44:13
371520,2016-03-19 19:53:49,turbo_defekt,privat,Angebot,3200,control,limousine,2004,manuell,225,leon,150000,5,benzin,seat,ja,2016-03-19 00:00:00,0,96465,2016-03-19 20:44:43
371521,2016-03-27 20:36:20,Opel_Zafira_1.6_Elegance_TÃœV_12/16,privat,Angebot,1150,control,bus,2000,manuell,0,zafira,150000,3,benzin,opel,nein,2016-03-27 00:00:00,0,26624,2016-03-29 10:17:23
371522,2016-03-21 09:50:58,Mitsubishi_Cold,privat,Angebot,0,control,NaN,2005,manuell,0,colt,150000,7,benzin,mitsubishi,ja,2016-03-21 00:00:00,0,2694,2016-03-21 10:42:49
371523,2016-03-14 17:48:27,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14 00:00:00,0,39576,2016-04-06 00:46:52
371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein,2016-03-05 00:00:00,0,26135,2016-03-11 18:17:12
371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,0,87439,2016-04-07 07:15:26
371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN,2016-03-20 00:00:00,0,40764,2016-03-24 12:45:21
371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,0,73326,2016-03-22 03:17:10

In [2]:
print(df.shape)
df.describe()

(371528, 20)

,price,yearOfRegistration,powerPS,kilometer,monthOfRegistration,nrOfPictures,postalCode
count,3.715280e+05,371528.000000,371528.000000,371528.000000,371528.000000,371528.0,371528.00000
mean,1.729514e+04,2004.577997,115.549477,125618.688228,5.734445,0.0,50820.66764
std,3.587954e+06,92.866598,192.139578,40112.337051,3.712412,0.0,25799.08247
min,0.000000e+00,1000.000000,0.000000,5000.000000,0.000000,0.0,1067.00000
25%,1.150000e+03,1999.000000,70.000000,125000.000000,3.000000,0.0,30459.00000
50%,2.950000e+03,2003.000000,105.000000,150000.000000,6.000000,0.0,49610.00000
75%,7.200000e+03,2008.000000,150.000000,150000.000000,9.000000,0.0,71546.00000
max,2.147484e+09,9999.000000,20000.000000,150000.000000,12.000000,0.0,99998.00000

In [3]:
#df.drop(list(df[df['yearOfRegistration']>2017].index))
df=df[df['yearOfRegistration']>1950]
df=df[df['yearOfRegistration']<2018]
df

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÃœRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21
5,2016-04-04 17:36:23,BMW_316i___e36_Limousine___Bastlerfahrzeug__Ex...,privat,Angebot,650,test,limousine,1995,manuell,102,3er,150000,10,benzin,bmw,ja,2016-04-04 00:00:00,0,33775,2016-04-06 19:17:07
6,2016-04-01 20:48:51,Peugeot_206_CC_110_Platinum,privat,Angebot,2200,test,cabrio,2004,manuell,109,2_reihe,150000,8,benzin,peugeot,nein,2016-04-01 00:00:00,0,67112,2016-04-05 18:18:39
7,2016-03-21 18:54:38,VW_Derby_Bj_80__Scheunenfund,privat,Angebot,0,test,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein,2016-03-21 00:00:00,0,19348,2016-03-25 16:47:58
8,2016-04-04 23:42:13,Ford_C___Max_Titanium_1_0_L_EcoBoost,privat,Angebot,14500,control,bus,2014,manuell,125,c_max,30000,8,benzin,ford,NaN,2016-04-04 00:00:00,0,94505,2016-04-04 23:42:13
9,2016-03-17 10:53:50,VW_Golf_4_5_tuerig_zu_verkaufen_mit_Anhaengerk...,privat,Angebot,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN,2016-03-17 00:00:00,0,27472,2016-03-31 17:17:06
10,2016-03-26 19:54:18,Mazda_3_1.6_Sport,privat,Angebot,2000,control,limousine,2004,manuell,105,3_reihe,150000,12,benzin,mazda,nein,2016-03-26 00:00:00,0,96224,2016-04-06 10:45:34
11,2016-04-07 10:06:22,Volkswagen_Passat_Variant_2.0_TDI_Comfortline,privat,Angebot,2799,control,kombi,2005,manuell,140,passat,150000,12,diesel,volkswagen,ja,2016-04-07 00:00:00,0,57290,2016-04-07 10:25:17
12,2016-03-15 22:49:09,"VW_Passat_Facelift_35i__""7Sitzer""",privat,Angebot,999,control,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,NaN,2016-03-15 00:00:00,0,37269,2016-04-01 13:16:16
13,2016-03-21 21:37:40,VW_PASSAT_1.9_TDI_131_PS_LEDER,privat,Angebot,2500,control,kombi,2004,manuell,131,passat,150000,2,NaN,volkswagen,nein,2016-03-21 00:00:00,0,90762,2016-03-23 02:50:54
14,2016-03-21 12:57:01,Nissan_Navara_2.5DPF_SE4x4_Klima_Sitzheizg_Blu...,privat,Angebot,17999,control,suv,2011,manuell,190,navara,70000,3,diesel,nissan,nein,2016-03-21 00:00:00,0,4177,2016-04-06 07:45:42
16,2016-04-01 12:46:46,Polo_6n_1_4,privat,Angebot,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN,2016-04-01 00:00:00,0,38871,2016-04-01 12:46:46
17,2016-03-20 10:25:19,Renault_Twingo_1.2_16V_Aut.,privat,Angebot,1750,control,kleinwagen,2004,automatik,75,twingo,150000,2,benzin,renault,nein,2016-03-20 00:00:00,0,65599,2016-04-06 13:16:07
18,2016-03-23 15:48:05,Ford_C_MAX_2.0_TDCi_DPF_Titanium,privat,Angebot,7550,test,bus,2007,manuell,136,c_max,150000,6,diesel,ford,nein,2016-03-23 00:00:00,0,88361,2016-04-05 18:45:11
19,2016-04-01 22:55:47,Mercedes_Benz_A_160_Classic_Klima,privat,Angebot,1850,test,bus,2004,manuell,102,a_klasse,150000,1,benzin,mercedes_benz,nein,2016-04-01 00:00:00,0,49565,2016-04-05 22:46:05
20,2016-04-01 19:56:48,Volkswagen_Scirocco_1.4_TSI_Sport,privat,Angebot,10400,control,coupe,2009,manuell,160,scirocco,100000,4,benzin,volkswagen,nein,2016-04-01 00:00:00,0,75365,2016-04-05 16:45:49
21,2016-03-27 11:38:00,BMW_530i_TÃœV_7/17_Scheckheftgepflegt_sehr_gute...,privat,Angebot,3699,test,limousine,2002,automatik,231,5er,150000,7,benzin,bmw,nein,2016-03-27 00:00:00,0,68309,2016-04-07 06:44:26
23,2016-03-12 19:43:07,Stadtflitzer,privat,Angebot,450,test,kleinwagen,1997,manuell,50,arosa,150000,5,benzin,seat,nein,2016-03-12 00:00:00,0,9526,2016-03-21 01:46:11
24,2016-03-13 20:40:49,MERCEDES_200E__TÃœV_04/2016,privat,Angebot,500,test,limousine,1990,manuell,118,andere,150000,10,benzin,mercedes_benz,ja,2016-03-13 00:00:00,0,35390,2016-03-13 20:40:49
25,2016-03-18 21:44:09,BMW_530d_touring_Vollausstattung_NAVI,privat,Angebot,2500,control,kombi,2002,automatik,193,5er,150000,9,diesel,bmw,ja,2016-03-18 00:00:00,0,73765,2016-03-18 21:44:09
26,2016-03-10 19:38:18,Citroen_C4_Grand_Picasso.,privat,Angebot,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein,2016-03-10 00:00:00,0,31139,2016-03-16 09:16:46
27,2016-03-07 12:51:23,Honda_Civic_1.4_i_VTEC_Comfort,privat,Angebot,6900,test,limousine,2008,manuell,99,civic,60000,11,benzin,honda,nein,2016-03-07 00:00:00,0,12621,2016-03-26 09:44:53
28,2016-03-09 11:56:38,Volkswagen_T3_andere,privat,Angebot,1990,test,bus,1981,manuell,50,transporter,5000,1,benzin,volkswagen,nein,2016-03-09 00:00:00,0,87471,2016-03-10 07:44:33
29,2016-03-08 19:55:19,Fiat_Punto_1.2,privat,Angebot,690,test,kleinwagen,2003,manuell,60,punto,150000,3,benzin,fiat,nein,2016-03-08 00:00:00,0,86199,2016-03-09 11:45:28
30,2016-04-03 15:48:11,Mercedes_Benz_E_250_D_Original_Zustand_!!,privat,Angebot,3300,test,limousine,1995,automatik,113,e_klasse,150000,1,diesel,mercedes_benz,nein,2016-04-03 00:00:00,0,53879,2016-04-05 15:16:05
31,2016-03-29 16:57:02,Renault_clio_1.2_TÃœV_07/2016,privat,Angebot,899,control,NaN,2016,manuell,60,clio,150000,6,benzin,renault,NaN,2016-03-29 00:00:00,0,37075,2016-03-29 17:43:07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371498,2016-03-11 15:50:38,Opel_Vectra_Edition_100,privat,Angebot,699,control,limousine,1999,manuell,101,vectra,150000,3,benzin,opel,NaN,2016-03-11 00:00:00,0,65936,2016-03-17 12:44:29
371499,2016-03-08 13:52:00,OPEL_CORSA_B__ECO_SWING__TÃœV_1/17_8fach_Bereif...,privat,Angebot,600,control,kleinwagen,1998,manuell,54,corsa,150000,1,benzin,opel,nein,2016-03-08 00:00:00,0,24850,2016-03-13 00:16:40
371500,2016-03-21 23:40:49,Volkswagen_Golf_1.4_TSI_BlueMotion_Technology_...,privat,Angebot,20400,test,limousine,2014,automatik,150,golf,30000,9,benzin,volkswagen,nein,2016-03-21 00:00:00,0,38470,2016-04-07 04:17:32
371501,2016-03-26 18:36:54,Chrysler_Voyager,privat,Angebot,3900,test,bus,2003,automatik,174,voyager,150000,7,benzin,chrysler,nein,2016-03-26 00:00:00,0,34320,2016-04-06 09:16:04
371502,2016-04-01 12:59:21,Audi_A4_Avant_1.8,privat,Angebot,1600,test,kombi,1998,manuell,125,a4,150000,2,benzin,audi,nein,2016-04-01 00:00:00,0,34414,2016-04-07 09:44:29
371503,2016-04-01 01:55:58,Subaru_Justy_1.3,privat,Angebot,1700,control,kleinwagen,1999,manuell,68,justy,70000,11,benzin,subaru,nein,2016-03-31 00:00:00,0,90439,2016-04-07 04:16:26
371504,2016-03-07 17:06:35,220_cdi_Benz,privat,Angebot,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN,2016-03-07 00:00:00,0,61169,2016-03-08 21:28:38
371505,2016-04-03 19:56:57,Opel_Astra_1.6_Caravan_Selection,privat,Angebot,800,test,kombi,2000,manuell,101,astra,150000,11,benzin,opel,ja,2016-04-03 00:00:00,0,58730,2016-04-05 20:45:39
371506,2016-03-20 18:47:59,Volkswagen_Golf_1.9_TDI_DPF_Goal_Rentnerfzg._1...,privat,Angebot,5900,test,limousine,2006,manuell,105,golf,150000,9,diesel,volkswagen,nein,2016-03-20 00:00:00,0,1217,2016-04-07 02:44:27
371507,2016-03-16 17:06:19,Gepflegter_Audi_a4_2.0tdi_xenon_ahk_klima_sche...,privat,Angebot,5999,test,kombi,2005,manuell,140,a4,150000,4,diesel,audi,NaN,2016-03-16 00:00:00,0,56472,2016-03-18 11:30:17
371508,2016-04-02 16:43:27,Opel_Astra_1.8,privat,Angebot,1400,control,limousine,2001,manuell,125,astra,150000,2,benzin,opel,nein,2016-04-02 00:00:00,0,23820,2016-04-06 15:18:04
371509,2016-03-11 23:40:32,LT_35_DIESEL_Gruene_Plakette....letzte_Gelegen...,privat,Angebot,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein,2016-03-11 00:00:00,0,87700,2016-03-12 14:16:51
371510,2016-03-06 21:11:23,Mercedes_benz_e_klasse_avangarde_220_cdi_grune...,privat,Angebot,6500,test,limousine,2003,automatik,145,e_klasse,150000,3,diesel,mercedes_benz,nein,2016-03-05 00:00:00,0,60437,2016-03-12 12:18:05
371511,2016-03-31 18:50:37,Audi_A3_1.8_T_Attraction,privat,Angebot,1999,control,limousine,1997,manuell,150,a3,150000,12,benzin,audi,nein,2016-03-31 00:00:00,0,4275,2016-04-06 12:46:41
371512,2016-03-25 18:48:06,Mercedes_Benz_E_400_CDI_Avantgarde,privat,Angebot,5000,test,limousine,2003,automatik,260,e_klasse,150000,12,diesel,mercedes_benz,ja,2016-03-25 00:00:00,0,90473,2016-04-07 00:44:51
371513,2016-03-21 15:36:22,Seat_Leon_1.9_TDI_4/5_Tueren,privat,Angebot,4400,control,limousine,2008,manuell,105,leon,150000,7,diesel,seat,nein,2016-03-21 00:00:00,0,45896,2016-04-06 15:45:01
371514,2016-04-04 11:45:16,Renault_1_4_ltr.16_V_Megane_Cabrio,privat,Angebot,999,control,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,NaN,2016-04-04 00:00:00,0,88477,2016-04-06 12:44:52
371515,2016-03-09 11:36:55,Skoda_Fabia_Kombi_1.4,privat,Angebot,1690,test,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,NaN,2016-03-09 00:00:00,0,18246,2016-04-04 08:15:30
371516,2016-04-04 09:57:12,Volkswagen_Lupo_1.0,privat,Angebot,1490,control,kleinwagen,1998,manuell,50,lupo,150000,9,benzin,volkswagen,nein,2016-04-04 00:00:00,0,48653,2016-04-06 11:17:13
371517,2016-03-28 13:48:07,Volkswagen_Golf_2.0_TDI_DPF_Team,privat,Angebot,7900,test,limousine,2010,manuell,140,golf,150000,7,diesel,volkswagen,nein,2016-03-28 00:00:00,0,75223,2016-04-02 18:16:20
371518,2016-04-02 20:37:03,Bmw_320_D_DPF_Touring_!!!,privat,Angebot,3999,test,kombi,2005,manuell,3,3er,150000,5,diesel,bmw,nein,2016-04-02 00:00:00,0,81825,2016-04-06 20:47:12
371519,2016-03-09 13:37:43,Alfa_Romeo_159_Jtdm_1.9_150_ps_13_600_km_top_voll,privat,Angebot,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein,2016-03-09 00:00:00,0,51371,2016-03-13 01:44:13
371520,2016-03-19 19:53:49,turbo_defekt,privat,Angebot,3200,control,limousine,2004,manuell,225,leon,150000,5,benzin,seat,ja,2016-03-19 00:00:00,0,96465,2016-03-19 20:44:43
371521,2016-03-27 20:36:20,Opel_Zafira_1.6_Elegance_TÃœV_12/16,privat,Angebot,1150,control,bus,2000,manuell,0,zafira,150000,3,benzin,opel,nein,2016-03-27 00:00:00,0,26624,2016-03-29 10:17:23
371522,2016-03-21 09:50:58,Mitsubishi_Cold,privat,Angebot,0,control,NaN,2005,manuell,0,colt,150000,7,benzin,mitsubishi,ja,2016-03-21 00:00:00,0,2694,2016-03-21 10:42:49
371523,2016-03-14 17:48:27,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14 00:00:00,0,39576,2016-04-06 00:46:52
371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein,2016-03-05 00:00:00,0,26135,2016-03-11 18:17:12
371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,0,87439,2016-04-07 07:15:26
371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN,2016-03-20 00:00:00,0,40764,2016-03-24 12:45:21
371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,0,73326,2016-03-22 03:17:10

In [4]:
df[df['vehicleType']=='suv'][df['gearbox']=='manuell'][df['model']=='tiguan']

C:\Users\simra\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
286,2016-03-30 23:56:48,VW_Tiguan_2.0_TDI_DPF_BlueMotion_Technology,privat,Angebot,12000,control,suv,2011,manuell,101,tiguan,150000,7,diesel,volkswagen,nein,2016-03-30 00:00:00,0,1069,2016-03-31 07:43:22
299,2016-03-19 16:40:33,VWTiguan_sehr_gepflegt,privat,Angebot,16150,test,suv,2011,manuell,150,tiguan,30000,4,benzin,volkswagen,nein,2016-03-19 00:00:00,0,6502,2016-04-07 02:15:37
542,2016-03-14 22:57:33,Volkswagen_Tiguan_Sport_&_Style_/_8_fach_berei...,privat,Angebot,18300,control,suv,2013,manuell,122,tiguan,40000,1,benzin,volkswagen,nein,2016-03-14 00:00:00,0,92685,2016-04-07 05:46:14
1232,2016-03-19 18:52:10,Sonderpreis_:_1.4_TSI__E_10___Start/Stop__sche...,privat,Angebot,16960,test,suv,2013,manuell,122,tiguan,30000,6,benzin,volkswagen,nein,2016-03-13 00:00:00,0,67067,2016-03-30 07:17:03
1977,2016-04-02 17:46:08,VW_Tiguan_1.4_TSI_R_Line_BMT,privat,Angebot,22222,control,suv,2013,manuell,160,tiguan,30000,12,benzin,volkswagen,nein,2016-04-02 00:00:00,0,40878,2016-04-06 17:16:01
3646,2016-03-19 17:54:53,Volkswagen_Tiguan_2.0_TDI_DPF_4Motion_Sport_&_...,privat,Angebot,10500,control,suv,2008,manuell,140,tiguan,150000,4,diesel,volkswagen,nein,2016-03-19 00:00:00,0,90482,2016-03-20 20:17:36
4584,2016-04-04 09:51:18,Volkswagen_Tiguan_2.0_TDI_DPF_4Motion_Life,privat,Angebot,23950,control,suv,2013,manuell,140,tiguan,70000,6,diesel,volkswagen,nein,2016-04-04 00:00:00,0,88316,2016-04-06 11:17:07
4719,2016-03-11 22:54:24,Volkswagen_Tiguan_2.0_TDI_DPF_4Motion_Sport_&_...,privat,Angebot,13800,control,suv,2008,manuell,140,tiguan,125000,8,diesel,volkswagen,nein,2016-03-11 00:00:00,0,44329,2016-04-05 12:44:46
6738,2016-03-19 18:45:24,Volkswagen_Tiguan_1.4_TSI_4Motion_Sport_&_Styl...,privat,Angebot,10900,test,suv,2008,manuell,150,tiguan,125000,5,benzin,volkswagen,nein,2016-03-19 00:00:00,0,36448,2016-03-28 23:15:34
9893,2016-04-04 23:50:56,"Volkswagen_Tiguan_2.0_TDI_DPF_BMT_""Life""",privat,Angebot,21900,control,suv,2014,manuell,140,tiguan,20000,1,diesel,volkswagen,nein,2016-04-04 00:00:00,0,48455,2016-04-07 09:15:21
9924,2016-03-31 13:26:34,Tiguan2_0_Diesel_BMT_Bj.11/2013;_mit_Garantie;...,privat,Angebot,21490,control,suv,2013,manuell,140,tiguan,70000,11,diesel,volkswagen,nein,2016-03-21 00:00:00,0,53577,2016-04-06 08:45:00
11171,2016-03-17 22:40:14,Volkswagen_Tiguan_2.0_TDI_DPF_BlueMotion_Techn...,privat,Angebot,14640,test,suv,2011,manuell,140,tiguan,150000,4,diesel,volkswagen,nein,2016-03-17 00:00:00,0,31787,2016-04-07 13:17:20
11565,2016-03-21 07:25:22,Tiguan2_0_Diesel_BMT__1.Hand,privat,Angebot,21490,test,suv,2013,manuell,140,tiguan,70000,11,diesel,volkswagen,nein,2016-03-21 00:00:00,0,53577,2016-04-06 09:17:36
11702,2016-03-28 23:38:40,Verkaufe_Tiguan__VW,privat,Angebot,14300,test,suv,2010,manuell,140,tiguan,150000,0,diesel,volkswagen,nein,2016-03-28 00:00:00,0,37603,2016-04-07 09:45:19
12392,2016-03-07 09:51:08,Tiguan_1.4___Bj.2013__29770_km___Panorama_Schi...,privat,Angebot,16960,control,suv,2013,manuell,122,tiguan,30000,6,benzin,volkswagen,nein,2016-03-07 00:00:00,0,67067,2016-04-02 02:45:28
12985,2016-03-19 17:45:41,Volkswagen_Tiguan_2.0_TDI_DPF_BlueMotion_Techn...,privat,Angebot,14000,control,suv,2010,manuell,140,tiguan,100000,2,diesel,volkswagen,nein,2016-03-19 00:00:00,0,66583,2016-03-27 09:18:06
13085,2016-03-19 22:57:01,Volkswagen_Tiguan_2.0_TDI_DPF_BlueMotion_Techn...,privat,Angebot,19950,test,suv,2012,manuell,140,tiguan,80000,11,diesel,volkswagen,nein,2016-03-19 00:00:00,0,52066,2016-03-29 14:44:41
13314,2016-03-15 18:53:08,Volkswagen_Tiguan_2.0_TDI_4Motion_R_Line_Sport...,privat,Angebot,13500,control,suv,2011,manuell,170,tiguan,150000,5,diesel,volkswagen,nein,2016-03-15 00:00:00,0,42111,2016-04-06 20:45:57
14633,2016-04-03 13:54:10,Volkswagen_Tiguan_2.0_TDI_SCR_BlueMotion_Techn...,privat,Angebot,26900,control,suv,2015,manuell,150,tiguan,10000,11,diesel,volkswagen,nein,2016-04-03 00:00:00,0,32825,2016-04-05 12:46:42
15785,2016-03-27 13:58:25,Volkswagen_Tiguan_2.0_TDI_Track&Field_4Motion_...,privat,Angebot,6200,test,suv,2008,manuell,140,tiguan,125000,11,diesel,volkswagen,nein,2016-03-27 00:00:00,0,12053,2016-03-27 13:58:25
16090,2016-03-29 20:45:31,Volkswagen_Tiguan_1.4_TSI,privat,Angebot,15000,test,suv,2009,manuell,150,tiguan,60000,8,benzin,volkswagen,nein,2016-03-29 00:00:00,0,10997,2016-04-06 06:46:11
16363,2016-04-01 21:51:24,Volkswagen_Tiguan_2.0TDI_NOTVERKAUF_Grosse_Nav...,privat,Angebot,12200,test,suv,2008,manuell,140,tiguan,90000,8,diesel,volkswagen,nein,2016-04-01 00:00:00,0,45883,2016-04-03 19:17:15
18093,2016-03-21 16:48:29,Volkswagen_Tiguan_2.0_TDI_DPF_BlueMotion_Techn...,privat,Angebot,20000,control,suv,2012,manuell,140,tiguan,60000,4,diesel,volkswagen,nein,2016-03-21 00:00:00,0,59229,2016-04-06 16:17:06
18475,2016-03-20 14:53:11,Volkswagen_Tiguan_1.4_TSI_BlueMotion_Technolog...,privat,Angebot,14590,test,suv,2011,manuell,122,tiguan,40000,11,benzin,volkswagen,nein,2016-03-20 00:00:00,0,31135,2016-03-30 05:45:10
18493,2016-03-25 13:48:01,Tiguan___Schiebedach____Park_Assist___Tempomat,privat,Angebot,16960,test,suv,2013,manuell,122,tiguan,40000,6,benzin,volkswagen,nein,2016-03-25 00:00:00,0,67067,2016-04-03 19:42:33
20949,2016-03-29 14:44:29,Verkaufe_gepflegten_Tiguan_Track_&_Field_4_MOT...,privat,Angebot,10750,test,suv,2009,manuell,140,tiguan,150000,1,diesel,volkswagen,nein,2016-03-29 00:00:00,0,31157,2016-04-04 11:17:41
22329,2016-03-23 14:36:44,Volkswagen_Tiguan_1.4_TSI_4Motion,privat,Angebot,10900,test,suv,2008,manuell,150,tiguan,100000,7,benzin,volkswagen,nein,2016-03-23 00:00:00,0,46284,2016-03-23 15:39:25
23025,2016-03-11 20:39:12,Volkswagen_VW_Tiguan_2.0_TDI_Panorama_TEAM_PLU...,privat,Angebot,15300,control,suv,2010,manuell,140,tiguan,80000,10,diesel,volkswagen,nein,2016-03-11 00:00:00,0,51375,2016-03-13 02:15:19
23644,2016-03-18 19:37:05,Volkswagen_Tiguan_2.0_TDI_DPF_4Motion,privat,Angebot,10900,control,suv,2009,manuell,170,tiguan,150000,3,diesel,volkswagen,nein,2016-03-18 00:00:00,0,73430,2016-03-22 11:16:33
24205,2016-03-25 14:55:42,Vw_Tiguan_Track_&_Field_*Garantie*_Allrad_4x4,privat,Angebot,11999,control,suv,2008,manuell,0,tiguan,125000,6,diesel,volkswagen,nein,2016-03-25 00:00:00,0,59199,2016-03-31 22:44:58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353831,2016-04-03 10:25:30,"SUV_VW_Tiguan__Sport&Style_Sonderserie_""Life__...",privat,Angebot,19900,control,suv,2013,manuell,122,tiguan,60000,11,benzin,volkswagen,nein,2016-04-03 00:00:00,0,63225,2016-04-06 16:47:10
354976,2016-03-11 10:56:44,Verkaufe_Top_gepflegten_VW_Tiguan_Bj.2008,privat,Angebot,10800,test,suv,2008,manuell,140,tiguan,150000,4,diesel,volkswagen,nein,2016-03-11 00:00:00,0,25709,2016-03-11 10:56:44
356019,2016-03-09 14:51:13,VW_Tiguan_Sport_&_Style__LEDER__Panorama__AHK_...,privat,Angebot,20990,test,suv,2012,manuell,160,tiguan,60000,6,benzin,volkswagen,nein,2016-03-09 00:00:00,0,74379,2016-04-06 19:46:30
356435,2016-03-28 10:50:05,Volkswagen_Tiguan_2.0_TDI_DPF_4Motion__Sport&S...,privat,Angebot,13500,control,suv,2008,manuell,140,tiguan,100000,5,diesel,volkswagen,nein,2016-03-28 00:00:00,0,81739,2016-04-06 12:45:19
356890,2016-03-11 00:59:24,Volkswagen_Tiguan_2.0_TSI_4Motion_Sport_&_Styl...,privat,Angebot,21900,test,suv,2012,manuell,179,tiguan,60000,9,benzin,volkswagen,nein,2016-03-10 00:00:00,0,63785,2016-04-06 05:44:48
357059,2016-03-21 14:51:26,Volkswagen_Tiguan_2.0_TDI_Sport_and_Style_19_Zoll,privat,Angebot,19900,control,suv,2014,manuell,110,tiguan,50000,4,diesel,volkswagen,nein,2016-03-21 00:00:00,0,89079,2016-04-06 12:15:39
357207,2016-03-29 10:50:11,Volkswagen_Tiguan_2.0_TDI_DPF_4Motion_Sport_&_...,privat,Angebot,10600,control,suv,2009,manuell,170,tiguan,150000,7,diesel,volkswagen,nein,2016-03-29 00:00:00,0,87549,2016-03-31 03:15:47
357471,2016-03-26 13:25:26,Volkswagen_Tiguan_1.4_TSI_4Motion_2.Hand,privat,Angebot,14200,control,suv,2009,manuell,150,tiguan,80000,1,benzin,volkswagen,nein,2016-03-26 00:00:00,0,61352,2016-04-06 12:45:30
357524,2016-03-23 13:47:36,Volkswagen_Tiguan_2.0_TDI_DPF_4Motion_Sport_&_...,privat,Angebot,19500,test,suv,2011,manuell,170,tiguan,70000,7,diesel,volkswagen,nein,2016-03-23 00:00:00,0,54295,2016-04-05 13:47:00
358443,2016-03-11 19:45:49,Tiguan_1.4__122_PS___Schiebe_Panodach___40_%_u...,privat,Angebot,16960,test,suv,2013,manuell,122,tiguan,30000,6,benzin,volkswagen,nein,2016-03-11 00:00:00,0,67067,2016-04-02 02:19:10
359256,2016-03-07 17:38:06,VW_Tiguan_2.0_TDI_4_Motion_Sport_&_Style,privat,Angebot,15500,test,suv,2009,manuell,140,tiguan,80000,9,diesel,volkswagen,nein,2016-03-07 00:00:00,0,82418,2016-04-06 05:15:51
359914,2016-03-27 14:45:29,Sehr_gepflegter_VW_tiguan,privat,Angebot,13800,control,suv,2009,manuell,140,tiguan,150000,0,diesel,volkswagen,ja,2016-03-27 00:00:00,0,28219,2016-04-07 11:15:56
361066,2016-03-23 21:50:23,Volkswagen_Tiguan_2.0_TDI_SCR_BlueMotionTech_S...,privat,Angebot,24250,test,suv,2016,manuell,110,tiguan,5000,1,diesel,volkswagen,nein,2016-03-23 00:00:00,0,73734,2016-03-25 06:47:13
361092,2016-03-27 16:59:56,VW_Tiguan_2.0_TDI__4Motion__Navi__Pano_uvm.,privat,Angebot,19500,test,suv,2012,manuell,140,tiguan,60000,7,diesel,volkswagen,nein,2016-03-27 00:00:00,0,46535,2016-04-05 10:45:02
362474,2016-03-20 21:54:33,Volkswagen_Tiguan_1.4_TSI___Leder___Panorama__...,privat,Angebot,11400,test,suv,2010,manuell,150,tiguan,150000,3,benzin,volkswagen,nein,2016-03-20 00:00:00,0,32108,2016-03-29 01:45:39
362517,2016-03-22 07:56:53,Volkswagen_Tiguan_1.4_TSI__Xenon__Navi__Rueckf...,privat,Angebot,11850,control,suv,2009,manuell,150,tiguan,80000,2,benzin,volkswagen,nein,2016-03-22 00:00:00,0,63303,2016-04-02 06:16:23
363198,2016-03-09 16:50:19,Volkswagen_Tiguan_2.0_TDI_DPF_Sport,privat,Angebot,10700,test,suv,2010,manuell,140,tiguan,150000,7,diesel,volkswagen,nein,2016-03-09 00:00:00,0,64283,2016-03-20 21:19:47
364975,2016-03-06 14:47:51,Volkswagen_Tiguan_1.4_TSI_BlueMotion_Technology,privat,Angebot,15899,control,suv,2011,manuell,122,tiguan,100000,9,benzin,volkswagen,nein,2016-03-06 00:00:00,0,91338,2016-03-08 04:15:55
365334,2016-04-01 00:55:59,Tiguan_2.0_TDI_4Motion___Silber,privat,Angebot,14800,test,suv,2008,manuell,140,tiguan,150000,8,diesel,volkswagen,nein,2016-04-01 00:00:00,0,26133,2016-04-01 08:41:58
366178,2016-03-20 17:53:50,Tiguan_Trend&Fun_1.4_TSI__90_kW_Blue_Motion_Te...,privat,Angebot,11350,test,suv,2010,manuell,122,tiguan,100000,8,benzin,volkswagen,nein,2016-03-20 00:00:00,0,45525,2016-04-07 00:46:31
366217,2016-03-12 17:52:56,Volkswagen_Tiguan_1.4_TSI_4Motion_Sport_&_Style,privat,Angebot,11500,test,suv,2008,manuell,150,tiguan,125000,1,benzin,volkswagen,nein,2016-03-12 00:00:00,0,51491,2016-04-07 10:16:44
367125,2016-03-24 06:03:23,Volkswagen_Tiguan_2.0_TDI_DPF_4Motion_Sport_&_...,privat,Angebot,9300,control,suv,2008,manuell,140,tiguan,150000,8,diesel,volkswagen,nein,2016-03-24 00:00:00,0,27628,2016-03-30 07:15:53
367147,2016-03-20 10:54:33,Volkswagen_Tiguan_1.4_TSI_4Motion_Trend_&_Fun,privat,Angebot,13500,control,suv,2008,manuell,150,tiguan,100000,8,benzin,volkswagen,nein,2016-03-20 00:00:00,0,78532,2016-03-29 21:18:26
368230,2016-03-23 19:44:52,Volkswagen_Tiguan_2.0_TSI_4Motion_Sport_&_Style,privat,Angebot,16900,control,suv,2010,manuell,200,tiguan,90000,7,benzin,volkswagen,nein,2016-03-23 00:00:00,0,67475,2016-04-06 00:44:48
369060,2016-03-13 00:58:09,VW_Tiguan_1.4_TSI_Blue_Motion_Tech._Schwarzmet...,privat,Angebot,17250,control,suv,2014,manuell,122,tiguan,30000,5,benzin,volkswagen,nein,2016-03-13 00:00:00,0,78141,2016-04-06 08:44:39
369165,2016-04-01 07:36:53,Volkswagen_Tiguan,privat,Angebot,19900,test,suv,2014,manuell,140,tiguan,125000,4,diesel,volkswagen,nein,2016-04-01 00:00:00,0,25364,2016-04-07 05:44:41
369215,2016-03-12 19:25:44,VW_Tiguan_4_Motion_Sport_&_Style,privat,Angebot,12800,control,suv,2009,manuell,170,tiguan,100000,2,benzin,volkswagen,NaN,2016-03-12 00:00:00,0,51570,2016-03-26 02:46:02
369661,2016-04-04 23:54:45,Volkswagen_Tiguan_1.4_TSI_BlueMotion_Technology,privat,Angebot,12980,control,suv,2010,manuell,150,tiguan,80000,6,benzin,volkswagen,nein,2016-04-04 00:00:00,0,91522,2016-04-07 09:15:24
370953,2016-03-24 17:46:36,Volkswagen_Tiguan_2.0_TDI_DPF_BlueMotion_Techn...,privat,Angebot,11000,control,suv,2011,manuell,110,tiguan,150000,4,diesel,volkswagen,nein,2016-03-24 00:00:00,0,89340,2016-04-03 10:19:25
371163,2016-03-22 11:50:50,Tiguan_2.0TDI_Bluemotion,privat,Angebot,8000,test,suv,2012,manuell,140,tiguan,70000,8,diesel,volkswagen,nein,2016-03-22 00:00:00,0,65479,2016-03-22 11:56:07

In [5]:
df.seller.unique()

array(['privat', 'gewerblich'], dtype=object)

In [6]:
df.groupby('seller').size()

seller
gewerblich         3
privat        367080
dtype: int64

In [7]:
del df['seller']

In [8]:
df

,dateCrawled,name,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-24 11:52:17,Golf_3_1.6,Angebot,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÃœRER,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21
5,2016-04-04 17:36:23,BMW_316i___e36_Limousine___Bastlerfahrzeug__Ex...,Angebot,650,test,limousine,1995,manuell,102,3er,150000,10,benzin,bmw,ja,2016-04-04 00:00:00,0,33775,2016-04-06 19:17:07
6,2016-04-01 20:48:51,Peugeot_206_CC_110_Platinum,Angebot,2200,test,cabrio,2004,manuell,109,2_reihe,150000,8,benzin,peugeot,nein,2016-04-01 00:00:00,0,67112,2016-04-05 18:18:39
7,2016-03-21 18:54:38,VW_Derby_Bj_80__Scheunenfund,Angebot,0,test,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein,2016-03-21 00:00:00,0,19348,2016-03-25 16:47:58
8,2016-04-04 23:42:13,Ford_C___Max_Titanium_1_0_L_EcoBoost,Angebot,14500,control,bus,2014,manuell,125,c_max,30000,8,benzin,ford,NaN,2016-04-04 00:00:00,0,94505,2016-04-04 23:42:13
9,2016-03-17 10:53:50,VW_Golf_4_5_tuerig_zu_verkaufen_mit_Anhaengerk...,Angebot,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN,2016-03-17 00:00:00,0,27472,2016-03-31 17:17:06
10,2016-03-26 19:54:18,Mazda_3_1.6_Sport,Angebot,2000,control,limousine,2004,manuell,105,3_reihe,150000,12,benzin,mazda,nein,2016-03-26 00:00:00,0,96224,2016-04-06 10:45:34
11,2016-04-07 10:06:22,Volkswagen_Passat_Variant_2.0_TDI_Comfortline,Angebot,2799,control,kombi,2005,manuell,140,passat,150000,12,diesel,volkswagen,ja,2016-04-07 00:00:00,0,57290,2016-04-07 10:25:17
12,2016-03-15 22:49:09,"VW_Passat_Facelift_35i__""7Sitzer""",Angebot,999,control,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,NaN,2016-03-15 00:00:00,0,37269,2016-04-01 13:16:16
13,2016-03-21 21:37:40,VW_PASSAT_1.9_TDI_131_PS_LEDER,Angebot,2500,control,kombi,2004,manuell,131,passat,150000,2,NaN,volkswagen,nein,2016-03-21 00:00:00,0,90762,2016-03-23 02:50:54
14,2016-03-21 12:57:01,Nissan_Navara_2.5DPF_SE4x4_Klima_Sitzheizg_Blu...,Angebot,17999,control,suv,2011,manuell,190,navara,70000,3,diesel,nissan,nein,2016-03-21 00:00:00,0,4177,2016-04-06 07:45:42
16,2016-04-01 12:46:46,Polo_6n_1_4,Angebot,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN,2016-04-01 00:00:00,0,38871,2016-04-01 12:46:46
17,2016-03-20 10:25:19,Renault_Twingo_1.2_16V_Aut.,Angebot,1750,control,kleinwagen,2004,automatik,75,twingo,150000,2,benzin,renault,nein,2016-03-20 00:00:00,0,65599,2016-04-06 13:16:07
18,2016-03-23 15:48:05,Ford_C_MAX_2.0_TDCi_DPF_Titanium,Angebot,7550,test,bus,2007,manuell,136,c_max,150000,6,diesel,ford,nein,2016-03-23 00:00:00,0,88361,2016-04-05 18:45:11
19,2016-04-01 22:55:47,Mercedes_Benz_A_160_Classic_Klima,Angebot,1850,test,bus,2004,manuell,102,a_klasse,150000,1,benzin,mercedes_benz,nein,2016-04-01 00:00:00,0,49565,2016-04-05 22:46:05
20,2016-04-01 19:56:48,Volkswagen_Scirocco_1.4_TSI_Sport,Angebot,10400,control,coupe,2009,manuell,160,scirocco,100000,4,benzin,volkswagen,nein,2016-04-01 00:00:00,0,75365,2016-04-05 16:45:49
21,2016-03-27 11:38:00,BMW_530i_TÃœV_7/17_Scheckheftgepflegt_sehr_gute...,Angebot,3699,test,limousine,2002,automatik,231,5er,150000,7,benzin,bmw,nein,2016-03-27 00:00:00,0,68309,2016-04-07 06:44:26
23,2016-03-12 19:43:07,Stadtflitzer,Angebot,450,test,kleinwagen,1997,manuell,50,arosa,150000,5,benzin,seat,nein,2016-03-12 00:00:00,0,9526,2016-03-21 01:46:11
24,2016-03-13 20:40:49,MERCEDES_200E__TÃœV_04/2016,Angebot,500,test,limousine,1990,manuell,118,andere,150000,10,benzin,mercedes_benz,ja,2016-03-13 00:00:00,0,35390,2016-03-13 20:40:49
25,2016-03-18 21:44:09,BMW_530d_touring_Vollausstattung_NAVI,Angebot,2500,control,kombi,2002,automatik,193,5er,150000,9,diesel,bmw,ja,2016-03-18 00:00:00,0,73765,2016-03-18 21:44:09
26,2016-03-10 19:38:18,Citroen_C4_Grand_Picasso.,Angebot,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein,2016-03-10 00:00:00,0,31139,2016-03-16 09:16:46
27,2016-03-07 12:51:23,Honda_Civic_1.4_i_VTEC_Comfort,Angebot,6900,test,limousine,2008,manuell,99,civic,60000,11,benzin,honda,nein,2016-03-07 00:00:00,0,12621,2016-03-26 09:44:53
28,2016-03-09 11:56:38,Volkswagen_T3_andere,Angebot,1990,test,bus,1981,manuell,50,transporter,5000,1,benzin,volkswagen,nein,2016-03-09 00:00:00,0,87471,2016-03-10 07:44:33
29,2016-03-08 19:55:19,Fiat_Punto_1.2,Angebot,690,test,kleinwagen,2003,manuell,60,punto,150000,3,benzin,fiat,nein,2016-03-08 00:00:00,0,86199,2016-03-09 11:45:28
30,2016-04-03 15:48:11,Mercedes_Benz_E_250_D_Original_Zustand_!!,Angebot,3300,test,limousine,1995,automatik,113,e_klasse,150000,1,diesel,mercedes_benz,nein,2016-04-03 00:00:00,0,53879,2016-04-05 15:16:05
31,2016-03-29 16:57:02,Renault_clio_1.2_TÃœV_07/2016,Angebot,899,control,NaN,2016,manuell,60,clio,150000,6,benzin,renault,NaN,2016-03-29 00:00:00,0,37075,2016-03-29 17:43:07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371498,2016-03-11 15:50:38,Opel_Vectra_Edition_100,Angebot,699,control,limousine,1999,manuell,101,vectra,150000,3,benzin,opel,NaN,2016-03-11 00:00:00,0,65936,2016-03-17 12:44:29
371499,2016-03-08 13:52:00,OPEL_CORSA_B__ECO_SWING__TÃœV_1/17_8fach_Bereif...,Angebot,600,control,kleinwagen,1998,manuell,54,corsa,150000,1,benzin,opel,nein,2016-03-08 00:00:00,0,24850,2016-03-13 00:16:40
371500,2016-03-21 23:40:49,Volkswagen_Golf_1.4_TSI_BlueMotion_Technology_...,Angebot,20400,test,limousine,2014,automatik,150,golf,30000,9,benzin,volkswagen,nein,2016-03-21 00:00:00,0,38470,2016-04-07 04:17:32
371501,2016-03-26 18:36:54,Chrysler_Voyager,Angebot,3900,test,bus,2003,automatik,174,voyager,150000,7,benzin,chrysler,nein,2016-03-26 00:00:00,0,34320,2016-04-06 09:16:04
371502,2016-04-01 12:59:21,Audi_A4_Avant_1.8,Angebot,1600,test,kombi,1998,manuell,125,a4,150000,2,benzin,audi,nein,2016-04-01 00:00:00,0,34414,2016-04-07 09:44:29
371503,2016-04-01 01:55:58,Subaru_Justy_1.3,Angebot,1700,control,kleinwagen,1999,manuell,68,justy,70000,11,benzin,subaru,nein,2016-03-31 00:00:00,0,90439,2016-04-07 04:16:26
371504,2016-03-07 17:06:35,220_cdi_Benz,Angebot,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN,2016-03-07 00:00:00,0,61169,2016-03-08 21:28:38
371505,2016-04-03 19:56:57,Opel_Astra_1.6_Caravan_Selection,Angebot,800,test,kombi,2000,manuell,101,astra,150000,11,benzin,opel,ja,2016-04-03 00:00:00,0,58730,2016-04-05 20:45:39
371506,2016-03-20 18:47:59,Volkswagen_Golf_1.9_TDI_DPF_Goal_Rentnerfzg._1...,Angebot,5900,test,limousine,2006,manuell,105,golf,150000,9,diesel,volkswagen,nein,2016-03-20 00:00:00,0,1217,2016-04-07 02:44:27
371507,2016-03-16 17:06:19,Gepflegter_Audi_a4_2.0tdi_xenon_ahk_klima_sche...,Angebot,5999,test,kombi,2005,manuell,140,a4,150000,4,diesel,audi,NaN,2016-03-16 00:00:00,0,56472,2016-03-18 11:30:17
371508,2016-04-02 16:43:27,Opel_Astra_1.8,Angebot,1400,control,limousine,2001,manuell,125,astra,150000,2,benzin,opel,nein,2016-04-02 00:00:00,0,23820,2016-04-06 15:18:04
371509,2016-03-11 23:40:32,LT_35_DIESEL_Gruene_Plakette....letzte_Gelegen...,Angebot,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein,2016-03-11 00:00:00,0,87700,2016-03-12 14:16:51
371510,2016-03-06 21:11:23,Mercedes_benz_e_klasse_avangarde_220_cdi_grune...,Angebot,6500,test,limousine,2003,automatik,145,e_klasse,150000,3,diesel,mercedes_benz,nein,2016-03-05 00:00:00,0,60437,2016-03-12 12:18:05
371511,2016-03-31 18:50:37,Audi_A3_1.8_T_Attraction,Angebot,1999,control,limousine,1997,manuell,150,a3,150000,12,benzin,audi,nein,2016-03-31 00:00:00,0,4275,2016-04-06 12:46:41
371512,2016-03-25 18:48:06,Mercedes_Benz_E_400_CDI_Avantgarde,Angebot,5000,test,limousine,2003,automatik,260,e_klasse,150000,12,diesel,mercedes_benz,ja,2016-03-25 00:00:00,0,90473,2016-04-07 00:44:51
371513,2016-03-21 15:36:22,Seat_Leon_1.9_TDI_4/5_Tueren,Angebot,4400,control,limousine,2008,manuell,105,leon,150000,7,diesel,seat,nein,2016-03-21 00:00:00,0,45896,2016-04-06 15:45:01
371514,2016-04-04 11:45:16,Renault_1_4_ltr.16_V_Megane_Cabrio,Angebot,999,control,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,NaN,2016-04-04 00:00:00,0,88477,2016-04-06 12:44:52
371515,2016-03-09 11:36:55,Skoda_Fabia_Kombi_1.4,Angebot,1690,test,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,NaN,2016-03-09 00:00:00,0,18246,2016-04-04 08:15:30
371516,2016-04-04 09:57:12,Volkswagen_Lupo_1.0,Angebot,1490,control,kleinwagen,1998,manuell,50,lupo,150000,9,benzin,volkswagen,nein,2016-04-04 00:00:00,0,48653,2016-04-06 11:17:13
371517,2016-03-28 13:48:07,Volkswagen_Golf_2.0_TDI_DPF_Team,Angebot,7900,test,limousine,2010,manuell,140,golf,150000,7,diesel,volkswagen,nein,2016-03-28 00:00:00,0,75223,2016-04-02 18:16:20
371518,2016-04-02 20:37:03,Bmw_320_D_DPF_Touring_!!!,Angebot,3999,test,kombi,2005,manuell,3,3er,150000,5,diesel,bmw,nein,2016-04-02 00:00:00,0,81825,2016-04-06 20:47:12
371519,2016-03-09 13:37:43,Alfa_Romeo_159_Jtdm_1.9_150_ps_13_600_km_top_voll,Angebot,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein,2016-03-09 00:00:00,0,51371,2016-03-13 01:44:13
371520,2016-03-19 19:53:49,turbo_defekt,Angebot,3200,control,limousine,2004,manuell,225,leon,150000,5,benzin,seat,ja,2016-03-19 00:00:00,0,96465,2016-03-19 20:44:43
371521,2016-03-27 20:36:20,Opel_Zafira_1.6_Elegance_TÃœV_12/16,Angebot,1150,control,bus,2000,manuell,0,zafira,150000,3,benzin,opel,nein,2016-03-27 00:00:00,0,26624,2016-03-29 10:17:23
371522,2016-03-21 09:50:58,Mitsubishi_Cold,Angebot,0,control,NaN,2005,manuell,0,colt,150000,7,benzin,mitsubishi,ja,2016-03-21 00:00:00,0,2694,2016-03-21 10:42:49
371523,2016-03-14 17:48:27,Suche_t4___vito_ab_6_sitze,Angebot,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14 00:00:00,0,39576,2016-04-06 00:46:52
371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,Angebot,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein,2016-03-05 00:00:00,0,26135,2016-03-11 18:17:12
371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,Angebot,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,0,87439,2016-04-07 07:15:26
371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,Angebot,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN,2016-03-20 00:00:00,0,40764,2016-03-24 12:45:21
371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,Angebot,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,0,73326,2016-03-22 03:17:10

In [9]:
df.isnull().sum()

dateCrawled                0
name                       0
offerType                  0
price                      0
abtest                     0
vehicleType            33594
yearOfRegistration         0
gearbox                19457
powerPS                    0
model                  19706
kilometer                  0
monthOfRegistration        0
fuelType               31562
brand                      0
notRepairedDamage      70143
dateCreated                0
nrOfPictures               0
postalCode                 0
lastSeen                   0
dtype: int64

In [10]:
df=df[(df['powerPS']>10) & (df['powerPS']<500)]

In [11]:
df

,dateCrawled,name,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÃœRER,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21
5,2016-04-04 17:36:23,BMW_316i___e36_Limousine___Bastlerfahrzeug__Ex...,Angebot,650,test,limousine,1995,manuell,102,3er,150000,10,benzin,bmw,ja,2016-04-04 00:00:00,0,33775,2016-04-06 19:17:07
6,2016-04-01 20:48:51,Peugeot_206_CC_110_Platinum,Angebot,2200,test,cabrio,2004,manuell,109,2_reihe,150000,8,benzin,peugeot,nein,2016-04-01 00:00:00,0,67112,2016-04-05 18:18:39
7,2016-03-21 18:54:38,VW_Derby_Bj_80__Scheunenfund,Angebot,0,test,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein,2016-03-21 00:00:00,0,19348,2016-03-25 16:47:58
8,2016-04-04 23:42:13,Ford_C___Max_Titanium_1_0_L_EcoBoost,Angebot,14500,control,bus,2014,manuell,125,c_max,30000,8,benzin,ford,NaN,2016-04-04 00:00:00,0,94505,2016-04-04 23:42:13
9,2016-03-17 10:53:50,VW_Golf_4_5_tuerig_zu_verkaufen_mit_Anhaengerk...,Angebot,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN,2016-03-17 00:00:00,0,27472,2016-03-31 17:17:06
10,2016-03-26 19:54:18,Mazda_3_1.6_Sport,Angebot,2000,control,limousine,2004,manuell,105,3_reihe,150000,12,benzin,mazda,nein,2016-03-26 00:00:00,0,96224,2016-04-06 10:45:34
11,2016-04-07 10:06:22,Volkswagen_Passat_Variant_2.0_TDI_Comfortline,Angebot,2799,control,kombi,2005,manuell,140,passat,150000,12,diesel,volkswagen,ja,2016-04-07 00:00:00,0,57290,2016-04-07 10:25:17
12,2016-03-15 22:49:09,"VW_Passat_Facelift_35i__""7Sitzer""",Angebot,999,control,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,NaN,2016-03-15 00:00:00,0,37269,2016-04-01 13:16:16
13,2016-03-21 21:37:40,VW_PASSAT_1.9_TDI_131_PS_LEDER,Angebot,2500,control,kombi,2004,manuell,131,passat,150000,2,NaN,volkswagen,nein,2016-03-21 00:00:00,0,90762,2016-03-23 02:50:54
14,2016-03-21 12:57:01,Nissan_Navara_2.5DPF_SE4x4_Klima_Sitzheizg_Blu...,Angebot,17999,control,suv,2011,manuell,190,navara,70000,3,diesel,nissan,nein,2016-03-21 00:00:00,0,4177,2016-04-06 07:45:42
16,2016-04-01 12:46:46,Polo_6n_1_4,Angebot,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN,2016-04-01 00:00:00,0,38871,2016-04-01 12:46:46
17,2016-03-20 10:25:19,Renault_Twingo_1.2_16V_Aut.,Angebot,1750,control,kleinwagen,2004,automatik,75,twingo,150000,2,benzin,renault,nein,2016-03-20 00:00:00,0,65599,2016-04-06 13:16:07
18,2016-03-23 15:48:05,Ford_C_MAX_2.0_TDCi_DPF_Titanium,Angebot,7550,test,bus,2007,manuell,136,c_max,150000,6,diesel,ford,nein,2016-03-23 00:00:00,0,88361,2016-04-05 18:45:11
19,2016-04-01 22:55:47,Mercedes_Benz_A_160_Classic_Klima,Angebot,1850,test,bus,2004,manuell,102,a_klasse,150000,1,benzin,mercedes_benz,nein,2016-04-01 00:00:00,0,49565,2016-04-05 22:46:05
20,2016-04-01 19:56:48,Volkswagen_Scirocco_1.4_TSI_Sport,Angebot,10400,control,coupe,2009,manuell,160,scirocco,100000,4,benzin,volkswagen,nein,2016-04-01 00:00:00,0,75365,2016-04-05 16:45:49
21,2016-03-27 11:38:00,BMW_530i_TÃœV_7/17_Scheckheftgepflegt_sehr_gute...,Angebot,3699,test,limousine,2002,automatik,231,5er,150000,7,benzin,bmw,nein,2016-03-27 00:00:00,0,68309,2016-04-07 06:44:26
23,2016-03-12 19:43:07,Stadtflitzer,Angebot,450,test,kleinwagen,1997,manuell,50,arosa,150000,5,benzin,seat,nein,2016-03-12 00:00:00,0,9526,2016-03-21 01:46:11
24,2016-03-13 20:40:49,MERCEDES_200E__TÃœV_04/2016,Angebot,500,test,limousine,1990,manuell,118,andere,150000,10,benzin,mercedes_benz,ja,2016-03-13 00:00:00,0,35390,2016-03-13 20:40:49
25,2016-03-18 21:44:09,BMW_530d_touring_Vollausstattung_NAVI,Angebot,2500,control,kombi,2002,automatik,193,5er,150000,9,diesel,bmw,ja,2016-03-18 00:00:00,0,73765,2016-03-18 21:44:09
26,2016-03-10 19:38:18,Citroen_C4_Grand_Picasso.,Angebot,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein,2016-03-10 00:00:00,0,31139,2016-03-16 09:16:46
27,2016-03-07 12:51:23,Honda_Civic_1.4_i_VTEC_Comfort,Angebot,6900,test,limousine,2008,manuell,99,civic,60000,11,benzin,honda,nein,2016-03-07 00:00:00,0,12621,2016-03-26 09:44:53
28,2016-03-09 11:56:38,Volkswagen_T3_andere,Angebot,1990,test,bus,1981,manuell,50,transporter,5000,1,benzin,volkswagen,nein,2016-03-09 00:00:00,0,87471,2016-03-10 07:44:33
29,2016-03-08 19:55:19,Fiat_Punto_1.2,Angebot,690,test,kleinwagen,2003,manuell,60,punto,150000,3,benzin,fiat,nein,2016-03-08 00:00:00,0,86199,2016-03-09 11:45:28
30,2016-04-03 15:48:11,Mercedes_Benz_E_250_D_Original_Zustand_!!,Angebot,3300,test,limousine,1995,automatik,113,e_klasse,150000,1,diesel,mercedes_benz,nein,2016-04-03 00:00:00,0,53879,2016-04-05 15:16:05
31,2016-03-29 16:57:02,Renault_clio_1.2_TÃœV_07/2016,Angebot,899,control,NaN,2016,manuell,60,clio,150000,6,benzin,renault,NaN,2016-03-29 00:00:00,0,37075,2016-03-29 17:43:07
33,2016-03-25 21:48:47,BMW_325i_Aut.,Angebot,18000,test,limousine,2007,automatik,218,3er,20000,5,benzin,bmw,nein,2016-03-25 00:00:00,0,39179,2016-04-07 04:45:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371490,2016-03-22 10:37:54,Honda_Accord_Tourer_2.0_Lifestyle_Verhandlungs...,Angebot,13850,control,kombi,2012,manuell,156,accord,125000,10,benzin,honda,nein,2016-03-22 00:00:00,0,91301,2016-04-05 23:17:04
371491,2016-03-15 20:25:20,Volkswagen_Passat_2.0_Executive,Angebot,3200,test,limousine,2002,manuell,116,passat,150000,4,lpg,volkswagen,nein,2016-03-15 00:00:00,0,60439,2016-04-07 03:16:40
371494,2016-03-26 14:38:18,BMW_760_erst_110_000_km_letze_Chance_bis_Monta...,Angebot,11500,control,limousine,2004,automatik,445,7er,125000,0,benzin,bmw,NaN,2016-03-26 00:00:00,0,4107,2016-04-06 20:45:16
371496,2016-03-20 12:46:00,"Peugeot_206_CC_""Filou""",Angebot,3850,test,cabrio,2006,manuell,108,2_reihe,125000,2,NaN,peugeot,nein,2016-03-20 00:00:00,0,53947,2016-03-26 21:18:23
371497,2016-03-05 15:54:11,Opel_Astra_1.6_Caravan,Angebot,4900,control,kombi,2008,manuell,116,astra,150000,2,benzin,opel,nein,2016-03-05 00:00:00,0,88213,2016-04-05 18:44:48
371498,2016-03-11 15:50:38,Opel_Vectra_Edition_100,Angebot,699,control,limousine,1999,manuell,101,vectra,150000,3,benzin,opel,NaN,2016-03-11 00:00:00,0,65936,2016-03-17 12:44:29
371499,2016-03-08 13:52:00,OPEL_CORSA_B__ECO_SWING__TÃœV_1/17_8fach_Bereif...,Angebot,600,control,kleinwagen,1998,manuell,54,corsa,150000,1,benzin,opel,nein,2016-03-08 00:00:00,0,24850,2016-03-13 00:16:40
371500,2016-03-21 23:40:49,Volkswagen_Golf_1.4_TSI_BlueMotion_Technology_...,Angebot,20400,test,limousine,2014,automatik,150,golf,30000,9,benzin,volkswagen,nein,2016-03-21 00:00:00,0,38470,2016-04-07 04:17:32
371501,2016-03-26 18:36:54,Chrysler_Voyager,Angebot,3900,test,bus,2003,automatik,174,voyager,150000,7,benzin,chrysler,nein,2016-03-26 00:00:00,0,34320,2016-04-06 09:16:04
371502,2016-04-01 12:59:21,Audi_A4_Avant_1.8,Angebot,1600,test,kombi,1998,manuell,125,a4,150000,2,benzin,audi,nein,2016-04-01 00:00:00,0,34414,2016-04-07 09:44:29
371503,2016-04-01 01:55:58,Subaru_Justy_1.3,Angebot,1700,control,kleinwagen,1999,manuell,68,justy,70000,11,benzin,subaru,nein,2016-03-31 00:00:00,0,90439,2016-04-07 04:16:26
371505,2016-04-03 19:56:57,Opel_Astra_1.6_Caravan_Selection,Angebot,800,test,kombi,2000,manuell,101,astra,150000,11,benzin,opel,ja,2016-04-03 00:00:00,0,58730,2016-04-05 20:45:39
371506,2016-03-20 18:47:59,Volkswagen_Golf_1.9_TDI_DPF_Goal_Rentnerfzg._1...,Angebot,5900,test,limousine,2006,manuell,105,golf,150000,9,diesel,volkswagen,nein,2016-03-20 00:00:00,0,1217,2016-04-07 02:44:27
371507,2016-03-16 17:06:19,Gepflegter_Audi_a4_2.0tdi_xenon_ahk_klima_sche...,Angebot,5999,test,kombi,2005,manuell,140,a4,150000,4,diesel,audi,NaN,2016-03-16 00:00:00,0,56472,2016-03-18 11:30:17
371508,2016-04-02 16:43:27,Opel_Astra_1.8,Angebot,1400,control,limousine,2001,manuell,125,astra,150000,2,benzin,opel,nein,2016-04-02 00:00:00,0,23820,2016-04-06 15:18:04
371509,2016-03-11 23:40:32,LT_35_DIESEL_Gruene_Plakette....letzte_Gelegen...,Angebot,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein,2016-03-11 00:00:00,0,87700,2016-03-12 14:16:51
371510,2016-03-06 21:11:23,Mercedes_benz_e_klasse_avangarde_220_cdi_grune...,Angebot,6500,test,limousine,2003,automatik,145,e_klasse,150000,3,diesel,mercedes_benz,nein,2016-03-05 00:00:00,0,60437,2016-03-12 12:18:05
371511,2016-03-31 18:50:37,Audi_A3_1.8_T_Attraction,Angebot,1999,control,limousine,1997,manuell,150,a3,150000,12,benzin,audi,nein,2016-03-31 00:00:00,0,4275,2016-04-06 12:46:41
371512,2016-03-25 18:48:06,Mercedes_Benz_E_400_CDI_Avantgarde,Angebot,5000,test,limousine,2003,automatik,260,e_klasse,150000,12,diesel,mercedes_benz,ja,2016-03-25 00:00:00,0,90473,2016-04-07 00:44:51
371513,2016-03-21 15:36:22,Seat_Leon_1.9_TDI_4/5_Tueren,Angebot,4400,control,limousine,2008,manuell,105,leon,150000,7,diesel,seat,nein,2016-03-21 00:00:00,0,45896,2016-04-06 15:45:01
371514,2016-04-04 11:45:16,Renault_1_4_ltr.16_V_Megane_Cabrio,Angebot,999,control,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,NaN,2016-04-04 00:00:00,0,88477,2016-04-06 12:44:52
371515,2016-03-09 11:36:55,Skoda_Fabia_Kombi_1.4,Angebot,1690,test,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,NaN,2016-03-09 00:00:00,0,18246,2016-04-04 08:15:30
371516,2016-04-04 09:57:12,Volkswagen_Lupo_1.0,Angebot,1490,control,kleinwagen,1998,manuell,50,lupo,150000,9,benzin,volkswagen,nein,2016-04-04 00:00:00,0,48653,2016-04-06 11:17:13
371517,2016-03-28 13:48:07,Volkswagen_Golf_2.0_TDI_DPF_Team,Angebot,7900,test,limousine,2010,manuell,140,golf,150000,7,diesel,volkswagen,nein,2016-03-28 00:00:00,0,75223,2016-04-02 18:16:20
371519,2016-03-09 13:37:43,Alfa_Romeo_159_Jtdm_1.9_150_ps_13_600_km_top_voll,Angebot,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein,2016-03-09 00:00:00,0,51371,2016-03-13 01:44:13
371520,2016-03-19 19:53:49,turbo_defekt,Angebot,3200,control,limousine,2004,manuell,225,leon,150000,5,benzin,seat,ja,2016-03-19 00:00:00,0,96465,2016-03-19 20:44:43
371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,Angebot,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein,2016-03-05 00:00:00,0,26135,2016-03-11 18:17:12
371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,Angebot,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,0,87439,2016-04-07 07:15:26
371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,Angebot,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN,2016-03-20 00:00:00,0,40764,2016-03-24 12:45:21
371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,Angebot,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,0,73326,2016-03-22 03:17:10

In [12]:
df[df['vehicleType'].isnull() & df['gearbox'].isnull() & df['fuelType'].isnull() & df['notRepairedDamage'].isnull()& df['model'].isnull()].size

3610

In [13]:
del df['nrOfPictures']
df.describe()

,price,yearOfRegistration,powerPS,kilometer,monthOfRegistration,postalCode
count,3.263750e+05,326375.000000,326375.000000,326375.000000,326375.000000,326375.000000
mean,1.002745e+04,2003.422762,125.353792,125755.434699,5.956198,51380.079491
std,5.649759e+05,7.066937,59.528589,39212.063518,3.599509,25816.514614
min,0.000000e+00,1951.000000,11.000000,5000.000000,0.000000,1067.000000
25%,1.300000e+03,1999.000000,80.000000,100000.000000,3.000000,31020.000000
50%,3.300000e+03,2004.000000,116.000000,150000.000000,6.000000,50374.000000
75%,7.800000e+03,2008.000000,150.000000,150000.000000,9.000000,72275.000000
max,1.000000e+08,2017.000000,495.000000,150000.000000,12.000000,99998.000000

In [14]:
df

,dateCrawled,name,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,postalCode,lastSeen
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÃœRER,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,60437,2016-04-06 10:17:21
5,2016-04-04 17:36:23,BMW_316i___e36_Limousine___Bastlerfahrzeug__Ex...,Angebot,650,test,limousine,1995,manuell,102,3er,150000,10,benzin,bmw,ja,2016-04-04 00:00:00,33775,2016-04-06 19:17:07
6,2016-04-01 20:48:51,Peugeot_206_CC_110_Platinum,Angebot,2200,test,cabrio,2004,manuell,109,2_reihe,150000,8,benzin,peugeot,nein,2016-04-01 00:00:00,67112,2016-04-05 18:18:39
7,2016-03-21 18:54:38,VW_Derby_Bj_80__Scheunenfund,Angebot,0,test,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein,2016-03-21 00:00:00,19348,2016-03-25 16:47:58
8,2016-04-04 23:42:13,Ford_C___Max_Titanium_1_0_L_EcoBoost,Angebot,14500,control,bus,2014,manuell,125,c_max,30000,8,benzin,ford,NaN,2016-04-04 00:00:00,94505,2016-04-04 23:42:13
9,2016-03-17 10:53:50,VW_Golf_4_5_tuerig_zu_verkaufen_mit_Anhaengerk...,Angebot,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN,2016-03-17 00:00:00,27472,2016-03-31 17:17:06
10,2016-03-26 19:54:18,Mazda_3_1.6_Sport,Angebot,2000,control,limousine,2004,manuell,105,3_reihe,150000,12,benzin,mazda,nein,2016-03-26 00:00:00,96224,2016-04-06 10:45:34
11,2016-04-07 10:06:22,Volkswagen_Passat_Variant_2.0_TDI_Comfortline,Angebot,2799,control,kombi,2005,manuell,140,passat,150000,12,diesel,volkswagen,ja,2016-04-07 00:00:00,57290,2016-04-07 10:25:17
12,2016-03-15 22:49:09,"VW_Passat_Facelift_35i__""7Sitzer""",Angebot,999,control,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,NaN,2016-03-15 00:00:00,37269,2016-04-01 13:16:16
13,2016-03-21 21:37:40,VW_PASSAT_1.9_TDI_131_PS_LEDER,Angebot,2500,control,kombi,2004,manuell,131,passat,150000,2,NaN,volkswagen,nein,2016-03-21 00:00:00,90762,2016-03-23 02:50:54
14,2016-03-21 12:57:01,Nissan_Navara_2.5DPF_SE4x4_Klima_Sitzheizg_Blu...,Angebot,17999,control,suv,2011,manuell,190,navara,70000,3,diesel,nissan,nein,2016-03-21 00:00:00,4177,2016-04-06 07:45:42
16,2016-04-01 12:46:46,Polo_6n_1_4,Angebot,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN,2016-04-01 00:00:00,38871,2016-04-01 12:46:46
17,2016-03-20 10:25:19,Renault_Twingo_1.2_16V_Aut.,Angebot,1750,control,kleinwagen,2004,automatik,75,twingo,150000,2,benzin,renault,nein,2016-03-20 00:00:00,65599,2016-04-06 13:16:07
18,2016-03-23 15:48:05,Ford_C_MAX_2.0_TDCi_DPF_Titanium,Angebot,7550,test,bus,2007,manuell,136,c_max,150000,6,diesel,ford,nein,2016-03-23 00:00:00,88361,2016-04-05 18:45:11
19,2016-04-01 22:55:47,Mercedes_Benz_A_160_Classic_Klima,Angebot,1850,test,bus,2004,manuell,102,a_klasse,150000,1,benzin,mercedes_benz,nein,2016-04-01 00:00:00,49565,2016-04-05 22:46:05
20,2016-04-01 19:56:48,Volkswagen_Scirocco_1.4_TSI_Sport,Angebot,10400,control,coupe,2009,manuell,160,scirocco,100000,4,benzin,volkswagen,nein,2016-04-01 00:00:00,75365,2016-04-05 16:45:49
21,2016-03-27 11:38:00,BMW_530i_TÃœV_7/17_Scheckheftgepflegt_sehr_gute...,Angebot,3699,test,limousine,2002,automatik,231,5er,150000,7,benzin,bmw,nein,2016-03-27 00:00:00,68309,2016-04-07 06:44:26
23,2016-03-12 19:43:07,Stadtflitzer,Angebot,450,test,kleinwagen,1997,manuell,50,arosa,150000,5,benzin,seat,nein,2016-03-12 00:00:00,9526,2016-03-21 01:46:11
24,2016-03-13 20:40:49,MERCEDES_200E__TÃœV_04/2016,Angebot,500,test,limousine,1990,manuell,118,andere,150000,10,benzin,mercedes_benz,ja,2016-03-13 00:00:00,35390,2016-03-13 20:40:49
25,2016-03-18 21:44:09,BMW_530d_touring_Vollausstattung_NAVI,Angebot,2500,control,kombi,2002,automatik,193,5er,150000,9,diesel,bmw,ja,2016-03-18 00:00:00,73765,2016-03-18 21:44:09
26,2016-03-10 19:38:18,Citroen_C4_Grand_Picasso.,Angebot,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein,2016-03-10 00:00:00,31139,2016-03-16 09:16:46
27,2016-03-07 12:51:23,Honda_Civic_1.4_i_VTEC_Comfort,Angebot,6900,test,limousine,2008,manuell,99,civic,60000,11,benzin,honda,nein,2016-03-07 00:00:00,12621,2016-03-26 09:44:53
28,2016-03-09 11:56:38,Volkswagen_T3_andere,Angebot,1990,test,bus,1981,manuell,50,transporter,5000,1,benzin,volkswagen,nein,2016-03-09 00:00:00,87471,2016-03-10 07:44:33
29,2016-03-08 19:55:19,Fiat_Punto_1.2,Angebot,690,test,kleinwagen,2003,manuell,60,punto,150000,3,benzin,fiat,nein,2016-03-08 00:00:00,86199,2016-03-09 11:45:28
30,2016-04-03 15:48:11,Mercedes_Benz_E_250_D_Original_Zustand_!!,Angebot,3300,test,limousine,1995,automatik,113,e_klasse,150000,1,diesel,mercedes_benz,nein,2016-04-03 00:00:00,53879,2016-04-05 15:16:05
31,2016-03-29 16:57:02,Renault_clio_1.2_TÃœV_07/2016,Angebot,899,control,NaN,2016,manuell,60,clio,150000,6,benzin,renault,NaN,2016-03-29 00:00:00,37075,2016-03-29 17:43:07
33,2016-03-25 21:48:47,BMW_325i_Aut.,Angebot,18000,test,limousine,2007,automatik,218,3er,20000,5,benzin,bmw,nein,2016-03-25 00:00:00,39179,2016-04-07 04:45:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371490,2016-03-22 10:37:54,Honda_Accord_Tourer_2.0_Lifestyle_Verhandlungs...,Angebot,13850,control,kombi,2012,manuell,156,accord,125000,10,benzin,honda,nein,2016-03-22 00:00:00,91301,2016-04-05 23:17:04
371491,2016-03-15 20:25:20,Volkswagen_Passat_2.0_Executive,Angebot,3200,test,limousine,2002,manuell,116,passat,150000,4,lpg,volkswagen,nein,2016-03-15 00:00:00,60439,2016-04-07 03:16:40
371494,2016-03-26 14:38:18,BMW_760_erst_110_000_km_letze_Chance_bis_Monta...,Angebot,11500,control,limousine,2004,automatik,445,7er,125000,0,benzin,bmw,NaN,2016-03-26 00:00:00,4107,2016-04-06 20:45:16
371496,2016-03-20 12:46:00,"Peugeot_206_CC_""Filou""",Angebot,3850,test,cabrio,2006,manuell,108,2_reihe,125000,2,NaN,peugeot,nein,2016-03-20 00:00:00,53947,2016-03-26 21:18:23
371497,2016-03-05 15:54:11,Opel_Astra_1.6_Caravan,Angebot,4900,control,kombi,2008,manuell,116,astra,150000,2,benzin,opel,nein,2016-03-05 00:00:00,88213,2016-04-05 18:44:48
371498,2016-03-11 15:50:38,Opel_Vectra_Edition_100,Angebot,699,control,limousine,1999,manuell,101,vectra,150000,3,benzin,opel,NaN,2016-03-11 00:00:00,65936,2016-03-17 12:44:29
371499,2016-03-08 13:52:00,OPEL_CORSA_B__ECO_SWING__TÃœV_1/17_8fach_Bereif...,Angebot,600,control,kleinwagen,1998,manuell,54,corsa,150000,1,benzin,opel,nein,2016-03-08 00:00:00,24850,2016-03-13 00:16:40
371500,2016-03-21 23:40:49,Volkswagen_Golf_1.4_TSI_BlueMotion_Technology_...,Angebot,20400,test,limousine,2014,automatik,150,golf,30000,9,benzin,volkswagen,nein,2016-03-21 00:00:00,38470,2016-04-07 04:17:32
371501,2016-03-26 18:36:54,Chrysler_Voyager,Angebot,3900,test,bus,2003,automatik,174,voyager,150000,7,benzin,chrysler,nein,2016-03-26 00:00:00,34320,2016-04-06 09:16:04
371502,2016-04-01 12:59:21,Audi_A4_Avant_1.8,Angebot,1600,test,kombi,1998,manuell,125,a4,150000,2,benzin,audi,nein,2016-04-01 00:00:00,34414,2016-04-07 09:44:29
371503,2016-04-01 01:55:58,Subaru_Justy_1.3,Angebot,1700,control,kleinwagen,1999,manuell,68,justy,70000,11,benzin,subaru,nein,2016-03-31 00:00:00,90439,2016-04-07 04:16:26
371505,2016-04-03 19:56:57,Opel_Astra_1.6_Caravan_Selection,Angebot,800,test,kombi,2000,manuell,101,astra,150000,11,benzin,opel,ja,2016-04-03 00:00:00,58730,2016-04-05 20:45:39
371506,2016-03-20 18:47:59,Volkswagen_Golf_1.9_TDI_DPF_Goal_Rentnerfzg._1...,Angebot,5900,test,limousine,2006,manuell,105,golf,150000,9,diesel,volkswagen,nein,2016-03-20 00:00:00,1217,2016-04-07 02:44:27
371507,2016-03-16 17:06:19,Gepflegter_Audi_a4_2.0tdi_xenon_ahk_klima_sche...,Angebot,5999,test,kombi,2005,manuell,140,a4,150000,4,diesel,audi,NaN,2016-03-16 00:00:00,56472,2016-03-18 11:30:17
371508,2016-04-02 16:43:27,Opel_Astra_1.8,Angebot,1400,control,limousine,2001,manuell,125,astra,150000,2,benzin,opel,nein,2016-04-02 00:00:00,23820,2016-04-06 15:18:04
371509,2016-03-11 23:40:32,LT_35_DIESEL_Gruene_Plakette....letzte_Gelegen...,Angebot,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein,2016-03-11 00:00:00,87700,2016-03-12 14:16:51
371510,2016-03-06 21:11:23,Mercedes_benz_e_klasse_avangarde_220_cdi_grune...,Angebot,6500,test,limousine,2003,automatik,145,e_klasse,150000,3,diesel,mercedes_benz,nein,2016-03-05 00:00:00,60437,2016-03-12 12:18:05
371511,2016-03-31 18:50:37,Audi_A3_1.8_T_Attraction,Angebot,1999,control,limousine,1997,manuell,150,a3,150000,12,benzin,audi,nein,2016-03-31 00:00:00,4275,2016-04-06 12:46:41
371512,2016-03-25 18:48:06,Mercedes_Benz_E_400_CDI_Avantgarde,Angebot,5000,test,limousine,2003,automatik,260,e_klasse,150000,12,diesel,mercedes_benz,ja,2016-03-25 00:00:00,90473,2016-04-07 00:44:51
371513,2016-03-21 15:36:22,Seat_Leon_1.9_TDI_4/5_Tueren,Angebot,4400,control,limousine,2008,manuell,105,leon,150000,7,diesel,seat,nein,2016-03-21 00:00:00,45896,2016-04-06 15:45:01
371514,2016-04-04 11:45:16,Renault_1_4_ltr.16_V_Megane_Cabrio,Angebot,999,control,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,NaN,2016-04-04 00:00:00,88477,2016-04-06 12:44:52
371515,2016-03-09 11:36:55,Skoda_Fabia_Kombi_1.4,Angebot,1690,test,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,NaN,2016-03-09 00:00:00,18246,2016-04-04 08:15:30
371516,2016-04-04 09:57:12,Volkswagen_Lupo_1.0,Angebot,1490,control,kleinwagen,1998,manuell,50,lupo,150000,9,benzin,volkswagen,nein,2016-04-04 00:00:00,48653,2016-04-06 11:17:13
371517,2016-03-28 13:48:07,Volkswagen_Golf_2.0_TDI_DPF_Team,Angebot,7900,test,limousine,2010,manuell,140,golf,150000,7,diesel,volkswagen,nein,2016-03-28 00:00:00,75223,2016-04-02 18:16:20
371519,2016-03-09 13:37:43,Alfa_Romeo_159_Jtdm_1.9_150_ps_13_600_km_top_voll,Angebot,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein,2016-03-09 00:00:00,51371,2016-03-13 01:44:13
371520,2016-03-19 19:53:49,turbo_defekt,Angebot,3200,control,limousine,2004,manuell,225,leon,150000,5,benzin,seat,ja,2016-03-19 00:00:00,96465,2016-03-19 20:44:43
371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,Angebot,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein,2016-03-05 00:00:00,26135,2016-03-11 18:17:12
371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,Angebot,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,87439,2016-04-07 07:15:26
371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,Angebot,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN,2016-03-20 00:00:00,40764,2016-03-24 12:45:21
371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,Angebot,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,73326,2016-03-22 03:17:10

In [15]:
#df['offerType'].unique()
df.groupby('offerType').size()

offerType
Angebot    326371
Gesuch          4
dtype: int64

In [16]:
del df['dateCreated']
del df['lastSeen']

In [17]:
df.head()

,dateCrawled,name,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,postalCode
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,66954
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,90480
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÃœRER,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,91074
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,60437
5,2016-04-04 17:36:23,BMW_316i___e36_Limousine___Bastlerfahrzeug__Ex...,Angebot,650,test,limousine,1995,manuell,102,3er,150000,10,benzin,bmw,ja,33775

In [18]:
YEAR=pd.to_datetime(df['dateCrawled']).dt.year
df['age']=YEAR-df['yearOfRegistration']
df['age']

C:\Users\simra\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

1          5
2         12
3         15
4          8
5         21
6         12
7         36
8          2
9         18
10        12
11        11
12        21
13        12
14         5
16         0
17        12
18         9
19        12
20         7
21        14
23        19
24        26
25        14
26        -1
27         8
28        35
29        13
30        21
31         0
33         9
          ..
371490     4
371491    14
371494    12
371496    10
371497     8
371498    17
371499    18
371500     2
371501    13
371502    18
371503    17
371505    16
371506    10
371507    11
371508    15
371509    16
371510    13
371511    19
371512    13
371513     8
371514    16
371515    12
371516    18
371517     6
371519     0
371520    12
371524    16
371525    20
371526    14
371527     3
Name: age, Length: 326375, dtype: int64

In [19]:
del df['dateCrawled']

In [31]:
df=df.reset_index()
del df['index']

In [32]:
df

,name,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,postalCode,age
0,3112,0,3466,1,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,66954,5
1,78646,0,2492,1,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,90480,12
2,66849,0,642,1,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,91074,15
3,147716,0,1260,1,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,60437,8
4,23960,0,309,1,limousine,1995,manuell,102,3er,150000,10,benzin,bmw,ja,33775,21
5,126317,0,863,1,cabrio,2004,manuell,109,2_reihe,150000,8,benzin,peugeot,nein,67112,12
6,162049,0,0,1,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein,19348,36
7,56142,0,3103,0,bus,2014,manuell,125,c_max,30000,8,benzin,ford,NaN,94505,2
8,163824,0,458,1,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN,27472,18
9,84987,0,814,0,limousine,2004,manuell,105,3_reihe,150000,12,benzin,mazda,nein,96224,12
10,186433,0,1050,0,kombi,2005,manuell,140,passat,150000,12,diesel,volkswagen,ja,57290,11
11,167863,0,458,0,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,NaN,37269,21
12,166441,0,968,0,kombi,2004,manuell,131,passat,150000,2,NaN,volkswagen,nein,90762,12
13,105318,0,3446,0,suv,2011,manuell,190,navara,70000,3,diesel,nissan,nein,4177,5
14,130707,0,148,1,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN,38871,0
15,138482,0,724,0,kleinwagen,2004,automatik,75,twingo,150000,2,benzin,renault,nein,65599,12
16,55969,0,2114,1,bus,2007,manuell,136,c_max,150000,6,diesel,ford,nein,88361,9
17,89369,0,752,1,bus,2004,manuell,102,a_klasse,150000,1,benzin,mercedes_benz,nein,49565,12
18,188719,0,2579,0,coupe,2009,manuell,160,scirocco,100000,4,benzin,volkswagen,nein,75365,7
19,32355,0,1278,1,limousine,2002,automatik,231,5er,150000,7,benzin,bmw,nein,68309,14
20,152788,0,217,1,kleinwagen,1997,manuell,50,arosa,150000,5,benzin,seat,nein,9526,19
21,82640,0,238,1,limousine,1990,manuell,118,andere,150000,10,benzin,mercedes_benz,ja,35390,26
22,32252,0,968,0,kombi,2002,automatik,193,5er,150000,9,diesel,bmw,ja,73765,14
23,44867,0,1724,0,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein,31139,-1
24,74957,0,1993,1,limousine,2008,manuell,99,civic,60000,11,benzin,honda,nein,12621,8
25,189261,0,806,1,bus,1981,manuell,50,transporter,5000,1,benzin,volkswagen,nein,87471,35
26,53557,0,327,1,kleinwagen,2003,manuell,60,punto,150000,3,benzin,fiat,nein,86199,13
27,94615,0,1179,1,limousine,1995,automatik,113,e_klasse,150000,1,diesel,mercedes_benz,nein,53879,21
28,139933,0,411,0,NaN,2016,manuell,60,clio,150000,6,benzin,renault,NaN,37075,0
29,28253,0,3447,1,limousine,2007,automatik,218,3er,20000,5,benzin,bmw,nein,39179,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326345,74684,0,3021,0,kombi,2012,manuell,156,accord,125000,10,benzin,honda,nein,91301,4
326346,185449,0,1157,1,limousine,2002,manuell,116,passat,150000,4,lpg,volkswagen,nein,60439,14
326347,33390,0,2726,0,limousine,2004,automatik,445,7er,125000,0,benzin,bmw,NaN,4107,12
326348,126279,0,1316,1,cabrio,2006,manuell,108,2_reihe,125000,2,NaN,peugeot,nein,53947,10
326349,108504,0,1587,0,kombi,2008,manuell,116,astra,150000,2,benzin,opel,nein,88213,8
326350,120590,0,331,0,limousine,1999,manuell,101,vectra,150000,3,benzin,opel,NaN,65936,17
326351,106983,0,284,0,kleinwagen,1998,manuell,54,corsa,150000,1,benzin,opel,nein,24850,18
326352,179564,0,3625,1,limousine,2014,automatik,150,golf,30000,9,benzin,volkswagen,nein,38470,2
326353,44277,0,1336,1,bus,2003,automatik,174,voyager,150000,7,benzin,chrysler,nein,34320,13
326354,11693,0,676,1,kombi,1998,manuell,125,a4,150000,2,benzin,audi,nein,34414,18
326355,153055,0,714,0,kleinwagen,1999,manuell,68,justy,70000,11,benzin,subaru,nein,90439,17
326356,108592,0,374,1,kombi,2000,manuell,101,astra,150000,11,benzin,opel,ja,58730,16
326357,180628,0,1798,1,limousine,2006,manuell,105,golf,150000,9,diesel,volkswagen,nein,1217,10
326358,67405,0,1820,1,kombi,2005,manuell,140,a4,150000,4,diesel,audi,NaN,56472,11
326359,109110,0,604,0,limousine,2001,manuell,125,astra,150000,2,benzin,opel,nein,23820,15
326360,80899,0,774,1,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein,87700,16
326361,100958,0,1908,1,limousine,2003,automatik,145,e_klasse,150000,3,diesel,mercedes_benz,nein,60437,13
326362,8567,0,813,0,limousine,1997,manuell,150,a3,150000,12,benzin,audi,nein,4275,19
326363,95356,0,1614,1,limousine,2003,automatik,260,e_klasse,150000,12,diesel,mercedes_benz,ja,90473,13
326364,145634,0,1462,0,limousine,2008,manuell,105,leon,150000,7,diesel,seat,nein,45896,8
326365,133435,0,458,0,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,NaN,88477,16
326366,148094,0,708,1,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,NaN,18246,12
326367,184353,0,636,0,kleinwagen,1998,manuell,50,lupo,150000,9,benzin,volkswagen,nein,48653,18
326368,181338,0,2183,1,limousine,2010,manuell,140,golf,150000,7,diesel,volkswagen,nein,75223,6
326369,4990,0,1662,0,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein,51371,0
326370,200673,0,1157,0,limousine,2004,manuell,225,leon,150000,5,benzin,seat,ja,96465,12
326371,152331,0,522,1,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein,26135,16
326372,184968,0,2395,1,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein,87439,20
326373,164997,0,1201,1,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN,40764,14
326374,35373,0,4196,0,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein,73326,3

In [34]:
from sklearn import preprocessing, cross_validation
for cols in df.columns:
    #if df[cols].dtype == object:
    df[cols]= preprocessing.LabelEncoder().fit_transform(df[cols])

TypeError: '>' not supported between instances of 'str' and 'float'

In [36]:
t=df

C:\Users\simra\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,name,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,postalCode,age
0,3112,0,sgdhh,1,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,66954,5
1,78646,0,2492,1,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,90480,12
2,66849,0,642,1,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,91074,15
3,147716,0,1260,1,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,60437,8
4,23960,0,309,1,limousine,1995,manuell,102,3er,150000,10,benzin,bmw,ja,33775,21
5,126317,0,863,1,cabrio,2004,manuell,109,2_reihe,150000,8,benzin,peugeot,nein,67112,12
6,162049,0,0,1,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein,19348,36
7,56142,0,3103,0,bus,2014,manuell,125,c_max,30000,8,benzin,ford,NaN,94505,2
8,163824,0,458,1,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN,27472,18
9,84987,0,814,0,limousine,2004,manuell,105,3_reihe,150000,12,benzin,mazda,nein,96224,12
10,186433,0,1050,0,kombi,2005,manuell,140,passat,150000,12,diesel,volkswagen,ja,57290,11
11,167863,0,458,0,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,NaN,37269,21
12,166441,0,968,0,kombi,2004,manuell,131,passat,150000,2,NaN,volkswagen,nein,90762,12
13,105318,0,3446,0,suv,2011,manuell,190,navara,70000,3,diesel,nissan,nein,4177,5
14,130707,0,148,1,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN,38871,0
15,138482,0,724,0,kleinwagen,2004,automatik,75,twingo,150000,2,benzin,renault,nein,65599,12
16,55969,0,2114,1,bus,2007,manuell,136,c_max,150000,6,diesel,ford,nein,88361,9
17,89369,0,752,1,bus,2004,manuell,102,a_klasse,150000,1,benzin,mercedes_benz,nein,49565,12
18,188719,0,2579,0,coupe,2009,manuell,160,scirocco,100000,4,benzin,volkswagen,nein,75365,7
19,32355,0,1278,1,limousine,2002,automatik,231,5er,150000,7,benzin,bmw,nein,68309,14
20,152788,0,217,1,kleinwagen,1997,manuell,50,arosa,150000,5,benzin,seat,nein,9526,19
21,82640,0,238,1,limousine,1990,manuell,118,andere,150000,10,benzin,mercedes_benz,ja,35390,26
22,32252,0,968,0,kombi,2002,automatik,193,5er,150000,9,diesel,bmw,ja,73765,14
23,44867,0,1724,0,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein,31139,-1
24,74957,0,1993,1,limousine,2008,manuell,99,civic,60000,11,benzin,honda,nein,12621,8
25,189261,0,806,1,bus,1981,manuell,50,transporter,5000,1,benzin,volkswagen,nein,87471,35
26,53557,0,327,1,kleinwagen,2003,manuell,60,punto,150000,3,benzin,fiat,nein,86199,13
27,94615,0,1179,1,limousine,1995,automatik,113,e_klasse,150000,1,diesel,mercedes_benz,nein,53879,21
28,139933,0,411,0,NaN,2016,manuell,60,clio,150000,6,benzin,renault,NaN,37075,0
29,28253,0,3447,1,limousine,2007,automatik,218,3er,20000,5,benzin,bmw,nein,39179,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326345,74684,0,3021,0,kombi,2012,manuell,156,accord,125000,10,benzin,honda,nein,91301,4
326346,185449,0,1157,1,limousine,2002,manuell,116,passat,150000,4,lpg,volkswagen,nein,60439,14
326347,33390,0,2726,0,limousine,2004,automatik,445,7er,125000,0,benzin,bmw,NaN,4107,12
326348,126279,0,1316,1,cabrio,2006,manuell,108,2_reihe,125000,2,NaN,peugeot,nein,53947,10
326349,108504,0,1587,0,kombi,2008,manuell,116,astra,150000,2,benzin,opel,nein,88213,8
326350,120590,0,331,0,limousine,1999,manuell,101,vectra,150000,3,benzin,opel,NaN,65936,17
326351,106983,0,284,0,kleinwagen,1998,manuell,54,corsa,150000,1,benzin,opel,nein,24850,18
326352,179564,0,3625,1,limousine,2014,automatik,150,golf,30000,9,benzin,volkswagen,nein,38470,2
326353,44277,0,1336,1,bus,2003,automatik,174,voyager,150000,7,benzin,chrysler,nein,34320,13
326354,11693,0,676,1,kombi,1998,manuell,125,a4,150000,2,benzin,audi,nein,34414,18
326355,153055,0,714,0,kleinwagen,1999,manuell,68,justy,70000,11,benzin,subaru,nein,90439,17
326356,108592,0,374,1,kombi,2000,manuell,101,astra,150000,11,benzin,opel,ja,58730,16
326357,180628,0,1798,1,limousine,2006,manuell,105,golf,150000,9,diesel,volkswagen,nein,1217,10
326358,67405,0,1820,1,kombi,2005,manuell,140,a4,150000,4,diesel,audi,NaN,56472,11
326359,109110,0,604,0,limousine,2001,manuell,125,astra,150000,2,benzin,opel,nein,23820,15
326360,80899,0,774,1,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein,87700,16
326361,100958,0,1908,1,limousine,2003,automatik,145,e_klasse,150000,3,diesel,mercedes_benz,nein,60437,13
326362,8567,0,813,0,limousine,1997,manuell,150,a3,150000,12,benzin,audi,nein,4275,19
326363,95356,0,1614,1,limousine,2003,automatik,260,e_klasse,150000,12,diesel,mercedes_benz,ja,90473,13
326364,145634,0,1462,0,limousine,2008,manuell,105,leon,150000,7,diesel,seat,nein,45896,8
326365,133435,0,458,0,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,NaN,88477,16
326366,148094,0,708,1,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,NaN,18246,12
326367,184353,0,636,0,kleinwagen,1998,manuell,50,lupo,150000,9,benzin,volkswagen,nein,48653,18
326368,181338,0,2183,1,limousine,2010,manuell,140,golf,150000,7,diesel,volkswagen,nein,75223,6
326369,4990,0,1662,0,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein,51371,0
326370,200673,0,1157,0,limousine,2004,manuell,225,leon,150000,5,benzin,seat,ja,96465,12
326371,152331,0,522,1,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein,26135,16
326372,184968,0,2395,1,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein,87439,20
326373,164997,0,1201,1,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN,40764,14
326374,35373,0,4196,0,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein,73326,3