# PANDAS Module

### IRIS Data Set

In [5]:
import numpy as np
import os
os.getcwd()

'C:\\Users\\simra\\ML\\Lectures\\Lectures\\Lecture2-Pandas,Matplotlib'

In [17]:
import pandas as pd

In [19]:
iris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')
iris

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
5    4.6  3.4  1.4  0.3     Iris-setosa
6    5.0  3.4  1.5  0.2     Iris-setosa
7    4.4  2.9  1.4  0.2     Iris-setosa
8    4.9  3.1  1.5  0.1     Iris-setosa
9    5.4  3.7  1.5  0.2     Iris-setosa
10   4.8  3.4  1.6  0.2     Iris-setosa
11   4.8  3.0  1.4  0.1     Iris-setosa
12   4.3  3.0  1.1  0.1     Iris-setosa
13   5.8  4.0  1.2  0.2     Iris-setosa
14   5.7  4.4  1.5  0.4     Iris-setosa
15   5.4  3.9  1.3  0.4     Iris-setosa
16   5.1  3.5  1.4  0.3     Iris-setosa
17   5.7  3.8  1.7  0.3     Iris-setosa
18   5.1  3.8  1.5  0.3     Iris-setosa
19   5.4  3.4  1.7  0.2     Iris-setosa
20   5.1  3.7  1.5  0.4     Iris-setosa
21   4.6  3.6  1.0  0.2     Iris-setosa
22   5.1  3.3  1.7  0.5     Iris-setosa
23   4.8  3.4  1.9  0.2     Iris-setosa
24   5.0  3.0  1.6  0.2     Iris-setosa
25   5.0  3.4  1.6  0.4     Iris-setosa
26   5.2  3.5  1.5  0.2     Iris-setosa
27   5.2  3.4  1.4  0.2     Iris-setosa
28   4.7  3.2  1.6  0.2     Iris-setosa
29   4.8  3.1  1.6  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
119  6.9  3.2  5.7  2.3  Iris-virginica
120  5.6  2.8  4.9  2.0  Iris-virginica
121  7.7  2.8  6.7  2.0  Iris-virginica
122  6.3  2.7  4.9  1.8  Iris-virginica
123  6.7  3.3  5.7  2.1  Iris-virginica
124  7.2  3.2  6.0  1.8  Iris-virginica
125  6.2  2.8  4.8  1.8  Iris-virginica
126  6.1  3.0  4.9  1.8  Iris-virginica
127  6.4  2.8  5.6  2.1  Iris-virginica
128  7.2  3.0  5.8  1.6  Iris-virginica
129  7.4  2.8  6.1  1.9  Iris-virginica
130  7.9  3.8  6.4  2.0  Iris-virginica
131  6.4  2.8  5.6  2.2  Iris-virginica
132  6.3  2.8  5.1  1.5  Iris-virginica
133  6.1  2.6  5.6  1.4  Iris-virginica
134  7.7  3.0  6.1  2.3  Iris-virginica
135  6.3  3.4  5.6  2.4  Iris-virginica
136  6.4  3.1  5.5  1.8  Iris-virginica
137  6.0  3.0  4.8  1.8  Iris-virginica
138  6.9  3.1  5.4  2.1  Iris-virginica
139  6.7  3.1  5.6  2.4  Iris-virginica
140  6.9  3.1  5.1  2.3  Iris-virginica
141  5.8  2.7  5.1  1.9  Iris-virginica
142  6.8  3.2  5.9  2.3  Iris-virginica
143  6.7  3.3  5.7  2.5  Iris-virginica
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [21]:
#return the type of iris dataset
type(iris)

pandas.core.frame.DataFrame

In [25]:
#returns top 5 rows of the data set
iris.head()
#returns specified no of rows from top
iris.head(10)

#returns last 5 rows of the data set
iris.tail()

     5.1  3.5  1.4  0.2     Iris-setosa
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

In [29]:
#returns header of each colums
iris.columns

#changes the header
iris.columns = ['sl','sw','pl','pw','flower_class']

iris.columns

Index(['sl', 'sw', 'pl', 'pw', 'flower_class'], dtype='object')

In [31]:
#returns a tuple (no of rows , no of columns)
iris.shape

(149, 5)

In [33]:
#returns type of each colums
iris.dtypes

sl              float64
sw              float64
pl              float64
pw              float64
flower_class     object
dtype: object

In [36]:
#returns sum,mean etc calculated on each column
iris.describe()

               sl          sw          pl          pw
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [40]:
#returns a dataframe true if value is null else false
pd.isnull(iris)

#returns the number of null values in each column
pd.isnull(iris).sum()

sl              0
sw              0
pl              0
pw              0
flower_class    0
dtype: int64

In [44]:
#returns a specified column
iris.sl


#returns specified rows and columns
iris.iloc[1:3 , 1:3]

#to print 0th row
iris.iloc[0:1]

    sl   sw   pl   pw flower_class
0  4.9  3.0  1.4  0.2  Iris-setosa

In [62]:
#to change the value to null
iris.iloc[1:3,1:3] = np.nan
iris.head()

iris.isnull()

IndexingError: Too many indexers

In [56]:
#changes Nan value in specified column
iris.sw.fillna(1,inplace = True)
iris.head()

AttributeError: 'Series' object has no attribute 'sw'

In [58]:
iris.pl.fillna(0,inplace = True)
iris.head()

AttributeError: 'Series' object has no attribute 'pl'

In [63]:
iris.iloc[0:1] = np.nan
iris.head()

0    NaN
1    0.0
2    0.0
3    1.4
4    1.7
Name: pl, dtype: float64

In [64]:
#drop the rows with Nan in it
iris.dropna(inplace = True)

In [65]:
#to reset the index
iris.reset_index(drop = Ture , inplace = True)

NameError: name 'Ture' is not defined